### ISSUE TITLE
Clicking next does not close keyboard

### ISSUE THREAD

**Issue by robisaks** [HeinrichReimer/material-intro#102]
Very minor and easy to work around, but when using a custom fragment, if you have an EditText in it with the keyboard up, going to the next slide wont close the keyboard.

**Comment by HeinrichReimer** [comment]
Keyboard handling is not really the purpose of this library. 
But you can fix this by simply adding a custom `OnPageChangeListener` as in [thisStackOverflow answer](http://stackoverflow.com/questions/11818916/programmatically-hide-soft-keyboard-in-viewpager-onpagechangelistener-onpagesele).
