### ISSUE TITLE
Title and Description not showing

### ISSUE THREAD

**Issue by cyanlabsid** [HeinrichReimer/material-intro#104]
Everything in this library goes fine but why the title and description not showing although I have follow the tutorial

```java
addSlide(new SimpleSlide.Builder()
                .title(R.string.choose_product)
                .description(R.string.create)
                .image(R.drawable.ic_logo_white)
                .background(R.color.colorPrimary)
                .backgroundDark(R.color.transparent)
                .build());
```

but the result just like this
![screenshot_2016-07-25-16-36-19-344](https://cloud.githubusercontent.com/assets/19144231/17096999/14d9c9fa-5286-11e6-98a8-e76ff6a03aae.jpeg)

can you tell me how to fix this?

**Comment by HeinrichReimer** [comment]
Well I guess there might be a problem because of this line:
```java
. backgroundDark(R.color.transparent)
```
You need to understand that the dark background is used to calculate the text color, status bar background and indicator dots color. Setting it transparent is not what you should do. Please try to set `backgroundDark()` to the darker orange from the status bar.
Please message me back again if that fixes your problem.

**Comment by HeinrichReimer** [comment]
@cyanlabsid did that work for you?

**Comment by searchy2** [comment]
I seem to have this issue as well. I am using the code from the sample project: 
```
        addSlide(new SimpleSlide.Builder()
                .title(R.string.slide1Title)
                .description(R.string.slide1Description)
                .image(R.drawable.art_material_metaphor)
                .background(R.color.color_material_metaphor)
                .backgroundDark(R.color.color_dark_material_metaphor)
                .build());
```

**Comment by searchy2** [comment]
As I suspected, this is a noob issue. The good old image pushing elements off screen issue. I was using the sample images and they were too big. After I resize them a bit/put them in a hdpi folder, everything was jimmy! 

@cyanlabsid your image might be too big :wink:

**Comment by HeinrichReimer** [comment]
Well I guess @searchy2 is right. You might use `SimpleSlide.Builder.scrollable(true)` to make the intro content scrollable if the content is too big.
