### ISSUE TITLE
Content bleeds into status bar when using translucent bars

### ISSUE THREAD

**Issue by Maxr1998** [HeinrichReimer/material-intro#11]
Example here:
![Screenshot](https://cloud.githubusercontent.com/assets/5903699/13232957/9b6930ee-d9b1-11e5-8aa0-1c35bb9b41f5.png)

To fix, you need to add an additional 25dp top margin to your layouts.

**Comment by HeinrichReimer** [comment]
This can't be done by a fixed padding. Status bar size is not the same on every Android device.
I have to take a look at this

**Comment by Maxr1998** [comment]
I didn't say it was fixed ;)
There are resources for this, I will link them later :)
(Or you lock at my LockView in my MaxLock repo..)

**Comment by HeinrichReimer** [comment]
I'm not sure but shouldn't `fitSystemWindows="false"` do the job?

**Comment by Maxr1998** [comment]
not really, as it then wouldn't show that nice looking translucent statusbar... you should try to determine if the activity supports translucent system bars, then add a margin with `getResources().getDimensionPixelSize(getResources().getIdentifier("status_bar_height", "dimen", "android")`
