### ISSUE TITLE
DescriptionHtml Text Align Justify inline CSS

### ISSUE THREAD

**Issue by developingwild** [HeinrichReimer/material-intro#115]
I am trying to style an paragraph in HTML, but it's not working. Is there any possibility to add inline styling/css support? As I don't know any other way to justify align the text in the description.
```
 addSlide(new SimpleSlide.Builder()
                .title("Cookies")
                .descriptionHtml("<p style='text-align:justify;color:purple'>Cookies never are round and square at the same time so you have to bake them in a special oven that can make them round and square at the same time, a magical oven</p>")
                .background(R.color.introColor)
                .backgroundDark(R.color.introDarkColor)
                .layout(R.layout.intro)
                .build());
```

**Comment by HeinrichReimer** [comment]
The HTML parsing is not part of this library. It just uses the `Html` class to parse basic HTML. If you need more advanced parsing you can use your own HTML parser and use `SimpleSlide.Builder.content(CharSequence)`. For more detailed information on the capabilities of `Html` please check the official Android docs.
