### ISSUE TITLE
Padding in Description

### ISSUE THREAD

**Issue by developingwild** [HeinrichReimer/material-intro#116]
Is it possible to add the possibility to define left and right paddings for the description? I would like to have some smaller description, but I don't want to go throught the hassle and create an custom slide.

**Comment by HeinrichReimer** [comment]
Yes, this is possible by using a custom layout. Just use `SimpleSlide.Builder.layout(R.layout.your_custom_layout)`

**Comment by developingwild** [comment]
Jup found it out, thanks
