### ISSUE TITLE
Change description/title/color programatically

### ISSUE THREAD

**Issue by ritu99** [HeinrichReimer/material-intro#118]
Being able to change the description, title and color programatically would be helpful for certain slides.

I can currently get a slide, but there's no way to access those textviews.

**Comment by HeinrichReimer** [comment]
If you use `SimpleSlide` the text color is automatically set by looking at your background color to ensure legibility. You can't change the text color manually. If you need that then create your own slide type by extending `Slide` or define your own layout and use `FragmentSlide.Builder.layout()`.
