### ISSUE TITLE
Error: Failed to resolve: com.heinrichreimersoftware:material-intro:1.5.7

### ISSUE THREAD

**Issue by gau4sar** [HeinrichReimer/material-intro#121]
I have added maven { url "https://jitpack.io" } in both the gradle files. And added the dependency compile 'com.heinrichreimersoftware:material-intro:1.5.7' in my app.gradle. But still the issue exits.

**Comment by HeinrichReimer** [comment]
Check if you included the dependency as described here: https://jitpack.io/#com.heinrichreimersoftware/material-intro/1.5.7
Make sure you include the maven repo in your **root** `build.gradle` and the actual dependency in your **module's** `build.gradle`.
May also be a short downtime on JitPack's side but I checked the gradle settings and the repo is definitely up on JitPack.

**Comment by gau4sar** [comment]
thank you for your response it was my mistake i actually added the dependency inside 

    buildscript {
        repositories {
            jcenter()
            mavenCentral()
            maven { url "https://jitpack.io" }
       }
    }

of the root build.gradle
