### ISSUE TITLE
Regression 1.5.8 - Recreate fragments when swiping is locked

### ISSUE THREAD

**Issue by kevinthecity** [HeinrichReimer/material-intro#125]
There seems to be a regression in 1.5.8 that prevents customs fragments from being interacted with if they have `canGoForward` set to false.

1. I have a custom fragment that has `canGoForward` overwritten with a boolean to return false until a condition is met in the custom fragment.
2. Tapping anywhere on the screen dismisses the keyboard and all touch events start getting eaten.

If you follow the code in the debugger, you'll eventually see that [notifyDatasetChanged()](https://github.com/HeinrichReimer/material-intro/blob/4d5af6dd64bf778ed34bf3f0e223ecb9395a1629/library/src/main/java/com/heinrichreimersoftware/materialintro/view/SwipeBlockableViewPager.java#L85) is called as soon as you tap on the screen, leading me to believe that the following commit is the offending commit.

https://github.com/HeinrichReimer/material-intro/commit/4d5af6dd64bf778ed34bf3f0e223ecb9395a1629

My guess is the intercept touch code is not working as expected for custom fragments, or that the locking logic isn't quite right. If you have a hard time reproducing I can try and create a sample project.

Heres a gif of what it looks like in practice.

![cantclickgif](https://cloud.githubusercontent.com/assets/1014106/18221526/881a1426-714c-11e6-8929-5ab2bdb93c30.gif)

**Comment by Daerex** [comment]
Hi! Same problem here. While canGoForward return false the widgets are locked. Greetings!

PD: Thanks for your hard work :)

**Comment by daniel-stoneuk** [comment]
Yeah, this is a pretty major bug. Same thing happening here. I am guessing that commit [4d5af6d](https://github.com/HeinrichReimer/material-intro/commit/4d5af6dd64bf778ed34bf3f0e223ecb9395a1629) was the culprit. This is way worse than the previous issue as it totally renders my login setup useless.

**Comment by daniel-stoneuk** [comment]
I have made a pull request with a fix. All working great now. 😄  #128
