### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by antonkazakov** [HeinrichReimer/material-intro#13]
You should probably update ur gradle library., because  setSkipEnabled(skipEnabled) and setFinishEnabled(finishEnabled) aren't working when using gradle.

**Comment by CeJienAJPC** [comment]
This [issue](https://github.com/HeinrichReimer/material-intro/issues/9) has been already addressed. Have to wait for the release of next library version

**Comment by HeinrichReimer** [comment]
I'm waiting for some other issues to be fixed before releasing the next milestone.
If you want to use `setSkipEnabled()`/`setFinishEnabled()` and need the latest library feautures just subscribe to the snapshot dependency:

````gradle
dependencies {
    compile 'com.heinrichreimersoftware:material-intro:-SNAPSHOT'
}
````

You can also have dependencies for specific commits. Refer to the jitpack site for further information.
