### ISSUE TITLE
Custom fragment Button onclick not working

### ISSUE THREAD

**Issue by sunil19822701** [HeinrichReimer/material-intro#134]
If used cangoforward in custom fragment then button onclick is not getting fired have to hit the button multiple times to get it the event fires in version 1.5.8 but the same code is working fine in versiong 1.5.7

**Comment by daniel-stoneuk** [comment]
Once again, this is fixed in the latest snapshot, as I fixed it in commit
2bb3fc3. If you want to use the latest version, replace the dependency with
this:
com.heinrichreimersoftware:material-intro:c68005f
That will use the latest commit, but will not change if something else or a
new bug is added to the library.

**Comment by sunil19822701** [comment]
ok working fine any plans to add animation effect whlie swipping slides and how to use the parallax while passing custom fragment if i pass layout to custom fragment parallax effects is shown but not whilw passing the fragment

**Comment by daniel-stoneuk** [comment]
What do you mean, can you record a video?

**Comment by HeinrichReimer** [comment]
@sunil19822701 to use the parallax effect you have to use one of the following layouts and add `app:layout_parallaxFactor="x"` where `x` is your parallax factor:

- `ParallaxFrameLayout` (as replacement for `FrameLayout`)
- `ParallaxRelativeLayout` (as replacement for `RelativeLayout`)
- `ParallaxLinearLayout` (as replacement for `LinearLayout`)

Read the parallax section in the readme for more information on the parallax effect.

**Comment by HeinrichReimer** [comment]
For custom slide animations you could use `PageTransformer` as you would do in a normal `ViewPager`

**Comment by sunil19822701** [comment]
i am using parallaxLinearLayout for fragment  
<com.heinrichreimersoftware.materialintro.view.parallax.ParallaxLinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    ... >

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_parallaxFactor="1"
        ... />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_parallaxFactor="1.25"
        ... />

</com.heinrichreimersoftware.materialintro.view.parallax.ParallaxLinearLayout>

javacode

final Slide UserInfoSlide=new FragmentSlide.Builder()
                .background(R.color.colorPrimary)
                .backgroundDark(R.color.colorPrimaryDark)
                .fragment(UserInfoSlide.newInstance())
                .build();
I dont see parallax effect for this but if change  this line in java code to 
.fragment(R.layout.layout_user_info.xml) // Passing only layout
then parallax effects works properly

and dont know how to use PageTransformer as i am at learning stage if u could provide me the example for same to work that with library that will be helpful to me
And i have work around by implementing Parallaxable class in fragment now i get the effect

**Comment by HeinrichReimer** [comment]
Ah yeah, your `UserInfoSlide` should either extend `ParallaxFragment` or `ParallaxSlideFragment`.

**Comment by sunil19822701** [comment]
ok and how can i add PageTransformer to animate slides

**Comment by HeinrichReimer** [comment]
After looking at the source again I think it's not yet possible but would be easy for me to implement. You should create a separate issue for the `PageTransformer` and I'm going to implement that next weekend.

**Comment by sunil19822701** [comment]
ok thanks i am opening new for pagetransformer and thanks for a wonderful library
