### ISSUE TITLE
SimpleSlide with "Permissions" button -> self removing ?

### ISSUE THREAD

**Issue by zoff99** [HeinrichReimer/material-intro#137]
Is there a way to just use SimpleSlide.java with "grant permissions" button, so that when all permissions are granted, the slide will remove itself and scroll to the next slide?
or is there a callback for that?

**Comment by HeinrichReimer** [comment]
It's not possible for `SimpleSlide` to remove itself after all permissions are granted. However you could use `SimpleSlide.Builder.permissions()` with as many permissions as you want which will override the CTA button to display "Grant permissions" until all permissions are granted. Navigation will also be blocked until that.

**Comment by zoff99** [comment]
is there a callback when all permissions are granted, that i can receive? and then remove that slide programmatically?

**Comment by HeinrichReimer** [comment]
There isn't a special listener for that.
However you can use a `NavigationPolicy` as a global listener and check the permissions yourself in `canGoForward()`.

**Comment by zoff99** [comment]
and can i programmatically remove a slide that is already showing?

**Comment by HeinrichReimer** [comment]
Yes

**Comment by zoff99** [comment]
how?

**Comment by HeinrichReimer** [comment]
`IntroActivity.removeSlide()`
The method arguments are pretty self explanatory. You can pass the slide itself or the position which you want to remove

**Comment by zoff99** [comment]
what i do now is:
```
SlideFragment sf = (SlideFragment) slide_1.getFragment();
sf.nextSlide();
```

and expose the method in SlideFragment (set to public):
```
public void nextSlide() {
.
.
.
}

```

this is much nicer, since now i can move to the next slide programmatically.
maybe you can expose this method in your version also?


![unbenannt](https://cloud.githubusercontent.com/assets/6833516/18560712/19f7036a-7b7d-11e6-981e-a3dbe27795a7.PNG)

**Comment by HeinrichReimer** [comment]
Well then why not call `IntroActivity.nextSlide()` directly? :D

You should _not_ use `SlideFragment.nextSlide()` from outside of the fragment.
