### ISSUE TITLE
Issue with User Stupidity Denying Permissions

### ISSUE THREAD

**Issue by searchy2** [HeinrichReimer/material-intro#139]
Problem: If the user selects "Do Not Remind Again" when going through the permissions and then presses Deny on the permission, the user will be stuck on the Permissions screen forever. The user is unable to grant the permission and Material Intro does not allow the user to advance. 

Solution: Blame the user? Not the most elegant solution but it seems appropriate here. Is there a better way though?

**Comment by sunil19822701** [comment]
You can use addonNavigationBlockLoistener and if the user is on setting slide then check for
ActivityCompat.shouldShowRequestPermissionRationale(CONTEXT,PERMISSION) if this returns false
show user snackbar with action to open settings of your app
Intent myAppSettings = new Intent();
                    myAppSettings.setAction(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
                    Uri uri = Uri.fromParts("package", getActivity().getPackageName(), null);
                    myAppSettings.setData(uri);
                    startActivityForResult(myAppSettings, appsettingReqCode);
this will take him to your apps setting panel from where user can provide permissions.

**Comment by HeinrichReimer** [comment]
As @sunil19822701 said...
Check out https://github.com/HeinrichReimer/material-intro/blob/3100a7ca893db446d5d68d361dbf81b1c1cb1980/library/src/main/java/com/heinrichreimersoftware/materialintro/app/IntroActivity.java#L1143

**Comment by HeinrichReimer** [comment]
Make sure you are calling this method with the right arguments: https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#shouldShowRequestPermissionRationale(android.app.Activity, java.lang.String)

**Comment by HeinrichReimer** [comment]
Link seems to be broken by markdown so here is the working link: [ActivityCompat.shouldShowRequestPermissionRationale(Activity, String)](https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#shouldShowRequestPermissionRationale(android.app.Activity, java.lang.String))
