### ISSUE TITLE
mindsdk 15 / does not work on 2.3.x

### ISSUE THREAD

**Issue by zoff99** [HeinrichReimer/material-intro#141]
what are the features that prevent it working on gingerbread?
can i cut some stuff to make it work on 2.3.x ?

**Comment by HeinrichReimer** [comment]
SDK 15 is the recommended min SDK in Android Studio.
Nearly all devices run on SDK15+ so there's simply no need to support lower versions.

**Comment by zoff99** [comment]
i disagree. but ok i must accept your answer.

what is the difference of your app to "https://github.com/PaoloRotolo/AppIntro" ?
appintro does support down to API11

**Comment by daniel-stoneuk** [comment]
material-intro has many more animations and is much better looking. There's a trade-off between sweet animations and design (which is what I presume this library's main goal is) and compatibility. I doubt it would even run well on an older device on gingerbread.

**Comment by HeinrichReimer** [comment]
This library supports 97% of active Android devices. I think that's enough. If you want to support the last 3% you have to use another library or fork this repo and adopt it.
