### ISSUE TITLE
Disable swipe to next 

### ISSUE THREAD

**Issue by afflick** [HeinrichReimer/material-intro#150]
Hi, 

I'm wondering if it is possible to disable the ability to swipe to the next slide for all of my slides?
This would just allow the user to click the next button on the bottom of the slide to progress instead of being able to swipe or click next. 

Kind regards, Alex.

**Comment by HeinrichReimer** [comment]
It is unintuitive and therefore not possible with this library to have different behavior of the next button and  a leftwards swipe.
Either block both actions or none.
If you want to block navigating forwards and backwards the thing your looking for is [`NavigationPolicy`](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/app/NavigationPolicy.java).
