### ISSUE TITLE
Ability to use color int instead of resource ID in SimpleSlide.Builder

### ISSUE THREAD

**Issue by Flowrome** [HeinrichReimer/material-intro#151]
Why having the builder to call only @ColorRes and not just a int? i'm having trouble to set multi themes colors just because they are saved in a local variable and not in a resource. So i can't use Color.parseColor(String color), there is a way to do it without completely change the library?

**Comment by HeinrichReimer** [comment]
Very similar to #152

**Comment by HeinrichReimer** [comment]
Merging with #193
