### ISSUE TITLE
Ability to use Drawable instead of resource ID in SimpleSlide.Builder

### ISSUE THREAD

**Issue by hrsalehi** [HeinrichReimer/material-intro#152]
Hello, 
I want to able use ```Drawable``` instances instead of setting resource id. Sometimes I want to use ```VectoreDrawable``` and sometimes maybe ```Drawable``` wich i use ```VectorDrawableCompat``` create method and get the drawable instance.
Another thing is I want to set ```TypeFace``` for texts inside slides.

**Comment by HeinrichReimer** [comment]
Very similar to #151

**Comment by HeinrichReimer** [comment]
Merging with #193
