### ISSUE TITLE
Merging with similar library: PaoloRotolo/AppIntro

### ISSUE THREAD

**Issue by Andrew-Quebe** [heinrichreimer/material-intro#153]
Would you be interested in merging this library with [AppIntro](https://github.com/PaoloRotolo/AppIntro)? I think yours has some awesome features that could be brought over to our library if you have the time. If not, that's cool too...just know the offer is open :)

**Comment by achuinard** [comment]
IMO there are some hacks in the other AppIntro library. Has anyone else out there done a more thorough evaluation of the two libraries? At first glance, this library supports the Get Started button with ease as well as landscape layouts.

**Comment by achuinard** [comment]
At the same time, I'm finding a few ahas with this library - the forced exit after the final slide, unable to be changed through a simple API call, seems pretty hacky too. The author has recommended starting another activity first, then starting the material intro activity. Other libraries at least allow the Get Started action to be set...

**Comment by HeinrichReimer** [comment]
This library focusses more on animations and an easy API while still being flexible.
My problem with merging this into AppIntro is that I think their API wasn't designed to be extendable. It started with the idea to implement most of the features as a part of the fragments, meaning that some animations like fading colors wouldn't even be possible. Also their idea of having two main layouts makes it pretty hard to animate things.

**Comment by HeinrichReimer** [comment]
@achuinard Having the ability to decide whether the fade effect is enabled or not could be reason enough for you to create a new issue here.
And of course you can overwrite the CTA button's click listener, either for a single slide or the default click listener.
I think I should create a little example in the Readme though.

**Comment by Andrew-Quebe** [comment]
@achuinard I'd be interested to know how you would end an activity other than calling `finish()`...there really isn't a way to force an activity to close other than calling that method. Sure, you could use `onActivityResult()` stuff, but why overcomplicate things? 

Regarding the double layouts, for a while now, I've wanted to just have one, but have kept quiet about that.

**Comment by achuinard** [comment]
Personally I am against forcing the close once the 'Done' button is clicked. My CTA 'Get Started' button and my 'Done' button actually send you to the same 'sign up' screen. I found it annoying that Done forced the close while Get Started I had to manually close myself.

Heinrich is right that his lib has more flexibility than the other.

I actually settled on https://github.com/TangoAgency/material-intro-screen which was more closely aligned to Heinrich's lib

Having to use jitpack for Heinrich's lib was kind of annoying

Maybe Heinrich and TangoAgency can work together?

**Comment by Andrew-Quebe** [comment]
@achuinard did you forget, or maybe miss the fact that AppIntro has an onDonePressed listener? All you need to do is call an Intent in that function. This library doesn't seem to do this to my knowledge...but I've only read the readme.

**Comment by achuinard** [comment]
No, I'm pretty much over the AppIntro library because of 1) I noticed setRetainInstance usage in the AppIntroBaseFragment and 2) I did not see supporting APIs for the Call to Action button.

All this being said, no library is perfect, and I appreciate the work of all 3 devs - the AppIntro guys, Heinrich, and TangoAgency.

**Comment by Andrew-Quebe** [comment]
Also @HeinrichReimer, the library fully supports animations...even custom ones. https://github.com/apl-devs/AppIntro#animations

**Comment by Andrew-Quebe** [comment]
@achuinard well, it is what it is. But the decision is ultimately the owner's...not a user of neither library in question.

Also, with all due respect to TangoAngency, the demo GIFs in the Readme make the library look awful...the functionality may be great, but the layouts specifically in those demos don't look appealing whatsoever. Granted, the demo app for AppIntro didn't look good either, which is why I'm in the process of rebuilding it.

**Comment by achuinard** [comment]
Tango had some padding issues indeed, they didn't look great. When using
their lib, I had to extend their SlideFragment and implement my own UI.

**Comment by Andrew-Quebe** [comment]
@achuinard and you'd rather do that than use Heinrich's or APL-Devs intro libraries. Interesting...interesting indeed.

**Comment by achuinard** [comment]
I'm willing to look at another lib again, but from a business perspective
I've already spent a few hours working on what should be a rather simple
intro screen. In the end, implementing a 3-slide ViewPager myself may have
even been the easiest. It's fun to play with the different libs, but my
time is limited :) - at the end of the day, we are talking about a 3-slide
ViewPager with 3 of the same fragments.

**Comment by Andrew-Quebe** [comment]
@achuinard at the end of the day, you've spent a few hours creating your own custom layout because the library you chose to use has horrible padding issues, and the (seemingly) most popular one uses a method you don't like, and the second most popular one uses Jitpack.

But at the end of the day, it's just a 3 page intro, and what library you use doesn't matter. :)

**Comment by HeinrichReimer** [comment]
To be honest I don't really care when 1 of 100 users has a very very specific use case that neither of the common libraries implements it.
To say it in other words:
From a business perspective it wouldn't make sense for us to implement a library. We could rather spend our time on client work.
Therefore I don't like it much when people complain about missing features from a business perspective.
If there's any feature missing go ahead and create a pull request. That's how open source works. You get something for free and you give something for free.
I think @Andrew-Quebe would agree with that.

**Comment by Andrew-Quebe** [comment]
^ 100% spot on.

**Comment by achuinard** [comment]
Who's complaining about missing features?

**Comment by HeinrichReimer** [comment]
Fun fact: I didn't know about material-intro-screen until now 😁
Seems like Tango Agency copied quite a bunch of material-intro's code 😀

**Comment by Andrew-Quebe** [comment]
@HeinrichReimer that's not good!

**Comment by achuinard** [comment]
2 hours ago you said 'you get something for free, you give something for free'. They have taken your code and done what they believe to be a better job. In addition, they give you credit since the description of the project starts with 'Inspired by Heinrich Reimer Material Intro'.

**Comment by HeinrichReimer** [comment]
I haven't said anything bad about that 😀

**Comment by Anutha02** [comment]
Hmmmm. Looks like I might try this.

**Comment by chimbori** [comment]
It doesn’t seem like this discussion is going anywhere. If there’s still interest, please submit PRs and we’ll consider them!
