### ISSUE TITLE
Goto next activity

### ISSUE THREAD

**Issue by mosi5505** [HeinrichReimer/material-intro#163]
Hi dear
I use your library in my application and want to go to Main activity after intro activity...
i used code below:
.buttonCtaClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) 
                        {
                            Intent main=new Intent(MainIntro.this,MainActivity.class);
                            startActivity(main);
                        }
                    })
but it doesn't work properly.
another problem is how to handle last slide scroll... after last slide if user want to scrollforward intro disappear and app is finished...
please say how can i handle this event and define code for buttonCtaClickListener...
with the best thanks for your wonderful library...

**Comment by HeinrichReimer** [comment]
Check out the [*sample*][26] if you want to show an activity after the intro.  
([_SplashActivity.java_][27], [_SplashIntroActivity.java_][28], [_FinishActivity.java_][29])
Basically you need to start your MainActivity first and then start the intro activity after that. That way users could have the fade effect at the end of the intro.
