### ISSUE TITLE
Ability to pass through 'canGoForward()'

### ISSUE THREAD

**Issue by AkshayChordiya** [HeinrichReimer/material-intro#165]
I was thinking to have function to forcefully pass `canGoForward()`.

Maybe function named 'forceNextSlide()'. It will directly head to next page.

**Comment by HeinrichReimer** [comment]
No, that would brake the API design. However you could use a custom `NavigationPolicy` to only permit going to the next slide in specific cases.
Or slides chould handle `canGoForward()` themselves by using a `FragmentSlide`.

**Comment by AkshayChordiya** [comment]
I'll explain you the use case. I have login page and then register page in
intro of my app.
Now user can't go forward unless he does login but for first time users I
have kept a Register button below the login button which should go to next
slide of Register.
As I have overrided `canGoForward()` the click on register button doesn't
go to `nextSlide()`.
I'll post some pictures to understand better.

**Comment by HeinrichReimer** [comment]
Yeah, basically you should have a custom `NavigationPolicy` for that.
That would be the semantic right way to implement that.
