### ISSUE TITLE
Custom Slide with finish/get started button

### ISSUE THREAD

**Issue by anaszakariyah** [HeinrichReimer/material-intro#167]
I want to make getStarted Button only on last Slide. I can get it done with adding OnPageListener and check last position in onPageSelected() function, then show cta button it. But since the CTA button position can't be changed and its a bit weird to suddenly show CTA button after swiping page, I want to instead using custom fragment.

The question is, can we make it the button inside the fragment to finish the intro? In your example I don't see this case. Using nextSlide() would be apporiate right? How to check the communication between fragment and activity? Using listener should work right?

-*-
EDIT:
I tried the custom Fragment. Two problem arise.

1) The layout does not match.
![screenshot_1485171469](https://cloud.githubusercontent.com/assets/9209302/22202564/46375e5a-e19b-11e6-915d-364851a2f1ac.png)
I don't know why the other part like images and text is omitted. This is the xml code.
```
<com.heinrichreimersoftware.materialintro.view.parallax.ParallaxLinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipToPadding="false"
    android:fitsSystemWindows="false"
    android:gravity="center"
    android:orientation="vertical"
    android:padding="@dimen/mi_baseline">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="@dimen/mi_baseline"
        app:layout_parallaxFactor="0.4"
        android:gravity="center"
        android:textAppearance="@style/TextAppearance.AppCompat.Subhead"
        android:textSize="15sp"
        android:fontFamily="sans-serif-medium"
        tools:ignore="UnusedAttribute"
        tools:text="@string/intro_3_description"/>

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/mi_baseline"
        android:paddingLeft="?actionBarSize"
        android:paddingRight="?actionBarSize"
        android:gravity="center"
        android:adjustViewBounds="true"
        tools:ignore="ContentDescription"
        tools:src="@drawable/ic_book_svg"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/mi_baseline"
        app:layout_parallaxFactor="0.5"
        android:gravity="center"
        android:textAppearance="@style/TextAppearance.AppCompat.Headline"
        android:fontFamily="sans-serif-medium"
        tools:ignore="UnusedAttribute"
        tools:text="@string/intro_3_title"/>

    <Button
        android:layout_marginTop="30dp"
        android:layout_marginBottom="20dp"
        android:id="@+id/getStarted"
        android:layout_width="250dp"
        android:layout_height="wrap_content"
        android:text="@string/intro_get_started"/>

</com.heinrichreimersoftware.materialintro.view.parallax.ParallaxLinearLayout>
```
I am adding the fragment using this code:
```
addSlide(new FragmentSlide.Builder()
                .background(R.color.app_dark_primary)
                .backgroundDark(R.color.app_light_primary)
                .fragment(IntroFinishFragment.newInstance())
                .build());
```

2. The custom GetStarted doesnt work as expected
This is my specification. BACK, NEXT, SKIP and FINISH disabled. I set it so it can only use swipe and then on the last one must click "my Custom Get Started" with this code:
```
//In introactivity
        setButtonBackFunction(BUTTON_BACK_FUNCTION_BACK);
        setButtonNextFunction(BUTTON_NEXT_FUNCTION_NEXT);
        setButtonBackVisible(false);
        setButtonNextVisible(false);
        setButtonCtaVisible(false);
```
The custom button inside fragment can be referenced with listener, I succeded with that, but I can't seem using nextSlide() when clicking the button with this code. If I try using BUTTON_NEXT_FUNCTION_NEXT_FINISH the last slide would be swipeable and I don't want that. Any Ideas? User must click the my custom "Get Started" to close the Intro. 

-*-

Oh bit of a question. I want to ask. Can I change the the indicator position and the other action button? I see that in library the IntroActivity simply set the activity layout on xml files. I tried to setLayout after super function with my own layout file with the same ids.. and of course it messed up :D The ability to make this changes would be cool if possible, for example to make the CTA button below the indicator instead above the indicator and so on.

Regards,
Anas

**Comment by HeinrichReimer** [comment]
So basically you only want to show the CTA button on a specific slide and hide it for the others?

**Comment by HeinrichReimer** [comment]
That could be achieved by setting an empty button from the activity and set a CTA button using the `SimpleSlide.Builder`.

**Comment by HeinrichReimer** [comment]
Regarding the layout: you could just overwrite the original main layout. I guess it should be `R.layout.mi_activity_intro`.
Just copy-paste the original XML from the repo and swap the two views in the XML.
