### ISSUE TITLE
Any way to handle special permissions?

### ISSUE THREAD

**Issue by rosenpin** [HeinrichReimer/material-intro#171]
Is it currently possible to have special permissions granted using this library.
Special permissions such as:

- Notification Access

- Draw over other apps

- Modify system settings..

Please let me know if it isn't possible, I will try my best to implement it

**Comment by HeinrichReimer** [comment]
As these require you to go to a separate screen they can't be used with `SlideBuilder`. However you can probably subclass it and implement the permission request process by yourself.

**Comment by rosenpin** [comment]
Pretty much what I ended up doing.
I though about creating a PR that would make this process seamless using this library, but I found that there are a lot of issues with special permissions, for example, apparently MIUI required users to grant draw over other apps permission manually using their own API to do so, so the default API for Android M+ might not work on all of their devices.
This is just an example, my point is that it wouldn't be the best idea to try and implement this feature into a library.
Thanks for your response
