### ISSUE TITLE
Pressing back on first slide skips the intro

### ISSUE THREAD

**Issue by nathan-osman** [HeinrichReimer/material-intro#173]
First off, I just wanted to say that this is an excellent library and is the only one of the three I tried that actually worked for my application. Thank you for spending the time to develop and maintain it.

I am starting the intro from my main activity like so:

    Intent introIntent = new Intent(this, MainIntroActivity.class);
    startActivity(introIntent);

In `MainIntroActivity`, I set the back button behavior as follows:

    setButtonBackFunction(BUTTON_BACK_FUNCTION_BACK);

When I launch the application, the intro appears as expected. However, if I press the back button on the first slide, the main activity is shown instead, effectively allowing the user to bypass the intro (which requires some important permissions).

I am assuming this is a bug, though it may be possible to work around it by overriding `onBackPressed()` and checking which page is displayed. The only problem is that I can't seem to find a method that retrieves the current page.

**Comment by daniel-stoneuk** [comment]
You could try running a check with shared preferences to see if the user has gone through the intro.

**Comment by nathan-osman** [comment]
> "You could try running a check with shared preferences to see if the user has gone through the intro."

That's a possibility, except I would then need to ensure that the preference was only set after the intro was finished.

**Comment by daniel-stoneuk** [comment]
Had a little go myself:

```java
addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
    @Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        Log.d(TAG, "onPageScrolled() called with: position = [" + position + "], positionOffset = [" + positionOffset + "], positionOffsetPixels = [" + positionOffsetPixels + "]");
        if ((position + 1) == getSlides().size() && positionOffset > 0.99f) {
            Toast.makeText(MainIntroActivity.this, "Intro Ended", Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    public void onPageSelected(int position) {
    }

    @Override
    public void onPageScrollStateChanged(int state) {

    }
});
```
Not sure how reliable it would be, but worked fine on my Nexus and the Toast was only shown once (guessing that there might be an issue if onPageScrolled doesn't get called as often on slower devices). If that's the case, you could decrease 0.99f to 0.98 or something.

**Comment by HeinrichReimer** [comment]
So basically finishing an activity is the correct behavior for an activity.
However material-intro implements activity results which you can use to close your `MainActivity` too:  
Start your intro using:
```java
startActivityForResult();
```
and 
```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (requestCode == <your request code>) {
        if (resultCode == RESULT_OK) {
            // User completed intro
        }
        else {
            // User cancelled the intro so we'll finish this activity too.
            finish();
        }
    }
}
```

Sample code can be found here: https://github.com/HeinrichReimer/material-intro/blob/master/app/src/main/java/com/heinrichreimersoftware/materialintro/demo/FinishActivity.java

**Comment by nathan-osman** [comment]
Ah, yes. Using `startActivityForResult()` will work perfectly. Thanks!

**Comment by joeykrim** [comment]
As a vote of confidence, I'm using the startActivityForResult to determine when the welcome screen activities end and to start analytics tracking of the main activity and it's working well!

Would be great to have this tidbit in an FAQ somewhere, as it also took me some time to sort out startActivityForResult as being the best workflow available.

**Comment by HeinrichReimer** [comment]
Well basically it's 100% the same as the splash screen demo

**Comment by HeinrichReimer** [comment]
https://github.com/HeinrichReimer/material-intro#pro-tip-splash-screens
