### ISSUE TITLE
Changing to MIT license

### ISSUE THREAD

**Issue by checklist** [HeinrichReimer/material-intro#176]
Hi,

It's a nice library and I though of using it for a new project. Unfortunately, you license is complex. I suggest you change it to MIT which is the most common open source license these days. Otherwise, it makes it difficult for others to use it.

Thanks in Advance!

**Comment by HeinrichReimer** [comment]
The Apache license is fairly common on Android. The AOSP as well as all the Android support libraries are released with that license. I have thought about using the MIT license before but in the end Apache's only limitation is to include the license notice inside your app which you have to do anyway when you're using one of the support libraries.
More details can be found here:  https://choosealicense.com/licenses/apache-2.0/
Do you have any questions about how to declare the Apache license in your app?

**Comment by checklist** [comment]
Hi.
Thanks for the response. I can see your side of it. I am just saying that many developers (and companies) have different criteria and hence the reason that in the past years OS has moved from Apache to MIT. I would say that simply because it is shorter ;-)

You can see as an example this library https://github.com/TangoAgency/material-intro-screen which uses MIT and is similar (even inspired by your work!). The way I (and I guess many others) work is by evaluating many options and using the easiest for us.

I am not criticising in any way. Just as feedback! All the best and thanks for the great library and your response!

**Comment by HeinrichReimer** [comment]
I see your point.
Still have to check whether changing from Apache to MIT license has any side effects for me.
I'll check that now and if it works I can change the license this afternoon.

**Comment by Sleeper9** [comment]
I'm far from being an expert of this topic, but perhaps you could consider double-licensing as well.

**Comment by HeinrichReimer** [comment]
I've read a very informative GitHub issue on bootstrap changing their license from Apache to MIT and I'm pretty confident that changing to MIT is possible and legal.

**Comment by HeinrichReimer** [comment]
@Sleeper9 what would be the benefit of double licensing?

**Comment by Sleeper9** [comment]
This way the recipients can decide which license fits their needs the most, and use your library according to that. This gives an extra freedom factor for them. I've seen a number of other libs with dual-licensing.

It can also mean that lazy developers like me don't have to update the "Libraries used & Licensing" section in my app. :wink: 
But after all, I completely agree moving to MIT as well.

**Comment by HeinrichReimer** [comment]
@checklist @Sleeper9 double checked APLv2 › MIT compatibility:
According to [this post](https://blog.gerv.net/2013/02/relicensing-when-do-you-have-to-ask/) and [this Wikipedia page](https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses) if I want to change the library license I have to ask every contributor.
I'll take some time to ask everyone and if everyone agrees I'll change the license.

**Comment by HeinrichReimer** [comment]
@Sleeper9 If I get this right the MIT license would be compatible with the Apache license so you could redistribute MIT code under the Apache license and thus don't have to change the license notice.
You wouldn't have to change the notice as long as you use a version of the library that has the APL.

**Comment by HeinrichReimer** [comment]
I've contacted every contributor, so when everyone agrees I'll change the license.

Mentioning all contributors here so they'll keep updated on the license change:
* @Maxr1998 
* @ritu99 
* @daniel-stoneuk 
* @OhMyLob 
* @iampkhan 
* @TheDorkKnightRises 
* @pinpong 
* @Jucedik 
* @SpongeBobSun 
* @julianostarek 
* @bkromhout 
* @shaishavgandhi05 
* @thakkaryash94

**Comment by HeinrichReimer** [comment]
*As a side note: I'm seeing this as an experiment. If this works with material-intro, I'll migrate the license in my other open source projects too.*

**Comment by TheDorkKnightRises** [comment]
Hey there! I have absolutely no issue with changing the licence, so you can check my name off that list too ☺

**Comment by ritu99** [comment]
I have no issue as well

**Comment by HeinrichReimer** [comment]
So @pinpong, @shaishavgandhi05 what do you think?
