### ISSUE TITLE
Can't find the library

### ISSUE THREAD

**Issue by OhhConti** [HeinrichReimer/material-intro#177]
Hi, I was trying to use your library but after adding it in the gradle file, it gives me an error :
Failed to resolve : com.heinrichreimersoftware:material-intro:1.6

**Comment by daniel-stoneuk** [comment]
Make sure you include

```
    repositories {
        maven { url 'https://jitpack.io' }
    }
```

**Comment by OhhConti** [comment]
I've already done it :(

**Comment by HeinrichReimer** [comment]
The library is up on JitPack so double- that you included their repo in the `allprojects` block.
Check their site for more information and copy-paste code: https://jitpack.io/#com.heinrichreimersoftware/material-intro/1.6
If that still won't work out please post the exact error log message from the Gradle console.

**Comment by OhhConti** [comment]
I've done it but nothing has improved, probably I choke where to put the code ?

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }


    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by HeinrichReimer** [comment]
Ok that may be the problem.
The Gradle build system distinguishes between the project level _build.gradle_ and the module's _build.gradle_.
So if your project/workspace is named **ExampleProject** and you want to use the dependency in a module called **app**, you'll find the project level Gradle file at `/path/to/ExampleProject/build.gradle` and the module level build file at `/path/to/ExampleProject/app/build.gradle`.

**Comment by OhhConti** [comment]
I know that there are 2 different files of Gradle 
So where I need to put 
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
and where

dependencies {
	        compile 'com.heinrichreimersoftware:material-intro:1.6'
	}

**Comment by HeinrichReimer** [comment]
No problem :)
