### ISSUE TITLE
activity_intro.xml clashes with local file using the same name

### ISSUE THREAD

**Issue by odin-** [HeinrichReimer/material-intro#179]
I had my own activity_intro.xml in my app, and when including your lib it tried to use my layout file, thus causing an exception. 

Would this be possible to fix in your lib? I renamed my activity_intro.xml to temporarily fix the issue.

**Comment by HeinrichReimer** [comment]
Would you mind creating a pull request for that just renaming the layout files (prefixing *mi_...*) and its references?
I'm currently on vacation so I can't really help until next week.
If you decide to create a PR it would be nice if you could rename the fragment layouts too :)

**Comment by odin-** [comment]
Sure no problem. Opened a PR. Hope it's OK.

**Comment by odin-** [comment]
I renamed all resources. If that's too much just tell me and I'll just rename frags and layout.

**Comment by HeinrichReimer** [comment]
No that's just fine! Haven't thought about that
