### ISSUE TITLE
Helper methods for snackbar?

### ISSUE THREAD

**Issue by odin-** [HeinrichReimer/material-intro#188]
What do you think about some helper methods to show the snackbar in the fragment? This since I need to do a IntroActivity cast to get the root content view:

    public void showSnackbar(CharSequence text, int duration) {
        View contentView = ((IntroActivity)getActivity()).findViewById(android.R.id.content);
        if (contentView != null) {
            Snackbar.make(contentView, text, duration).show();
        }
    }

    public void showSnackbar(int resId, int duration) {
        View contentView = ((IntroActivity)getActivity()).findViewById(android.R.id.content);
        if (contentView != null) {
            Snackbar.make(contentView, resId, duration).show();
        }
    }

**Comment by odin-** [comment]
On the other hand hiding "everything" isn't the way to go either, but in this case popping up errors/messages in the snackbar might be an important part of the material intro which makes it more OK...

**Comment by HeinrichReimer** [comment]
You don't have to cast to use `findViewById();`

**Comment by HeinrichReimer** [comment]
We could rather add a method like `getContentView()` to both `IntroActivity` and `SlideFragment`

**Comment by odin-** [comment]
OK so we'll skip showMessage/showSnackbar like method?

**Comment by HeinrichReimer** [comment]
Yes
