### ISSUE TITLE
ETA for next release?

### ISSUE THREAD

**Issue by odin-** [HeinrichReimer/material-intro#190]

**Comment by daniel-stoneuk** [comment]
For now you could just use this commit:

```
dependencies { 	 compile 'com.heinrichreimersoftware:material-intro:12090368c5' 	}
```

**Comment by HeinrichReimer** [comment]
ETA is next Thursday when I change the license too.

**Comment by odin-** [comment]
Ah didn't know I could use the commit id. Thanks.

**Comment by HeinrichReimer** [comment]
Sorry for the delay. Preparing a new release right now, should be out in an hour 🙈

**Comment by HeinrichReimer** [comment]
Version **1.6.2** is out.
Don't get confused, I just forgot to bump versions for **1.6.1** so the changelog can be found here:
https://github.com/HeinrichReimer/material-intro/releases/tag/1.6.1
