### ISSUE TITLE
OnNavigationBlocked called for all clients

### ISSUE THREAD

**Issue by odin-** [HeinrichReimer/material-intro#191]
I have 3 slides which got a OnNavigationBlocked-listener in each slide fragment class.

However, if I am in a slide and it is blocked all 3 slide fragment classes gets a call to OnNavigationBlocked.

I could use _position_ to filter out the correct listener but in the end it is a little bit annoying as I also need to tell each slide which item position it is to be able to do this.

Got any tips? Anything that can be improved or do I have to learn to live with it :-)

**Comment by HeinrichReimer** [comment]
Basically we can add a separate callback to the `SlideFragment` that will eliminate the position parameter and only fire if the slide at the position is the slide that created the listener. I'll look into this at Thursday when I'm at home again.

**Comment by HeinrichReimer** [comment]
Now you can set up a `OnPositionNavigationBlockedListener` where you only have to set up the position once at initialization.

**Comment by odin-** [comment]
Excellent. Thanks for your work!
