### ISSUE TITLE
Bugs in demo

### ISSUE THREAD

**Issue by MFlisar** [HeinrichReimer/material-intro#194]
1) when you scroll to any position != 0 and rotate the device, the function `finishIfNeeded` will close the activity
2) if I disable this behaviour and go to the permissions page and rotate the device, then I can swipe to the next page (without animation though)

Those bugs are not happening with the play store version, but with the on from the repo's master...

In my clone I added a function to disable the `finishIfNeeded` check before adding slides and enable them again afterwards, which solves 1, but the second thing still happens, I don't know yet why though...

**Comment by HeinrichReimer** [comment]
Alright the first thing is solved.

**Comment by HeinrichReimer** [comment]
The second thing has something to do with the `SwipeBlockableViewPager`. I'm investigating this.

**Comment by HeinrichReimer** [comment]
Solved the second issue.

**Comment by shruti-ahuja** [comment]
Facing the same issue. When can we get the fixed version?

**Comment by HeinrichReimer** [comment]
Today

**Comment by MFlisar** [comment]
Tried it, can confirm it's working basically...

I still see 2 problems:

* I start reading data from the internal storage in `onPageSelected` (one page after the permissions slide) and it happens, that the `ViewPager` does call this function after rotation shortly and trying to swipe => can't reproduce that now and it's simply solveable for me with checking the permissions again in the callback
* rotate device on the page with the permission, press back, there's a visual glitch, the `ViewPager` does scroll one page forward and then to the previous one

**Comment by MFlisar** [comment]
Saw another thing after trying around 50 times or so, it happened, that I could swipe over the permissions slide without granting the permission... Only once though in all this "tests"... Point one seems to be this issue...

I will solve that by forcefully scrolling back if the permission is not granted in `onPageSelected` for now to make sure, that this does not have any influence on my app...

**Comment by HeinrichReimer** [comment]
Does the glitch happen even in the latest commit?

**Comment by MFlisar** [comment]
I'll check, you just changed the layouts...

**Comment by MFlisar** [comment]
PS: It does not fit in here, but I would rethink the last change... You force people now to include `ConstraintLayout` and `DataBinding` to their projects for very simple slide layouts...

And the glitch happens in the last commits demo app as well... Just swipe to the permission slide, rotate the phone and press the hardware back button and you'll see it

**Comment by shruti-ahuja** [comment]
Why are you forcing us to include `ConstraintLayout` and `DataBinding` ...
