### ISSUE TITLE
Increase the Line Spacing for Slide Description

### ISSUE THREAD

**Issue by CeJienAJPC** [heinrichreimer/material-intro#196]
Thanks for the awesome library. With current line spacing, the description when containing more than a line of text looks tightly-packed. Please increase the line spacing.

`android:lineSpacingMultiplier="1.3"` would do good

Thanks again.

**Comment by HeinrichReimer** [comment]
Yeah this is a good idea! Let's use 1.25x as it's more common in typesetting.
Would you mind creating a pull request?

**Comment by CeJienAJPC** [comment]
I am sorry. I just now started to use GIT. My bad, not sure what a PR means/how it works. Sorry (humility at its peak :))

**Comment by CeJienAJPC** [comment]
I am sorry for not responding to you. I was offline for the entire week
