### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by shruti-ahuja** [HeinrichReimer/material-intro#198]
Facing crash when starting my activity

`Process: me.unfollowers.droid.dev, PID: 24863
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/databinding/DataBinderMapper;
at android.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:31)
at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
at com.heinrichreimersoftware.materialintro.app.IntroActivity.onCreate(IntroActivity.java:198)
`

**Comment by shruti-ahuja** [comment]
It was working fine upto commit Id `5db130c`. But getting this crash after you added `DataBinding`.

**Comment by marcodc74** [comment]
Hi, you have to add 
android {
    ....
    dataBinding {
        enabled = true
    }
} In your manifest
Refer to 
https://developer.android.com/topic/libraries/data-binding/index.html#build_environment

**Comment by shruti-ahuja** [comment]
thanks!! It worked. Just wanted to know is there any advantage of using DataBinding in an app?

**Comment by HeinrichReimer** [comment]
@shruti-ahuja I recommend you reading the [API docs on this](https://developer.android.com/topic/libraries/data-binding/index.html#data_binding_layout_files). There is a lot you can do with data binding.

I'll add a note in the Readme that you need to enable dataBinding in the module's `build.gradle`.
