### ISSUE TITLE
More slide types

### ISSUE THREAD

**Issue by HeinrichReimer** [HeinrichReimer/material-intro#2]
This issue should track progress of more slide types.

**Current slide types:**

- [`SimpleSlide`][1]: Standard slide featuring a title, short description and image like Google's intros.
- [`FragmentSlide`][2]: Custom slide containing a `Fragment` or a layout resource.
- [`Slide`][3]: Base slide. If you want to modify what's shown in your slide this is the way to go.

**Ideas:**

- `ParallaxSlide`: Slide that has multiple layers and creates a nice parallax effect.

[1]: https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java
[2]: https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/FragmentSlide.java
[3]: https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/Slide.java

**Comment by kabouzeid** [comment]
Base Slide could include a ``` public String[] get permissions() ``` and ask the user to grant them on Marshmallow.

**Comment by Maxr1998** [comment]
I suggest adding a CustomView slide, which allows adding a View instead of the image. I'll do a pull request later if I get to do it :+1:

**Comment by HeinrichReimer** [comment]
@Maxr1998 I think this is already possible using `FragmentSlide`.
@kabouzeid `SimpleSlide` now supports permission validation.

**Comment by Maxr1998** [comment]
Or a modified simple slide with custom layout. Forget about my suggestion :D

**Comment by HeinrichReimer** [comment]
@Maxr1998 just call `SimpleSlide.Builder.layout(R.layout.your_custom_layout)` and you should be done.

**Comment by Maxr1998** [comment]
That's what I did, and that's why I said forget about it :)

**Comment by HeinrichReimer** [comment]
@Maxr1998 Perfect!

Yes  I've seen it, have to take a look at it when I'm home.
