### ISSUE TITLE
Avoid restarting and restore state after performing landscape

### ISSUE THREAD

**Issue by AkshayChordiya** [HeinrichReimer/material-intro#20]
When the phone is rotated into landscape the `material-intro` not only starts from the beginning, it creates a new instance of all the slides that is the intro is showed 2 times.

**Comment by HeinrichReimer** [comment]
I can't reproduce this behavior on my devices. Which library version and which device are you using?

**Comment by AkshayChordiya** [comment]
I'm using SNAPSHOT of material-intro.

​Regards
,
​Akshay Chordiya

**Comment by Maxr1998** [comment]
For me, it doesn't show the startup two times, but he is right with recreation. The FragmentManager normally cares about retaining Fragments, etc. This is broken with this library, which means Fragments are recreated each rotation, and that wastes power and CPU cycles.

**Comment by Maxr1998** [comment]
Fun fact: if you rotate the device, the Fragments get recreated, but onCreateView doesn't get called, means permissionGranted is false, and doesn't get true, means you can't go forward anymore after rotation.

**Comment by Maxr1998** [comment]
Sadly, my fix doesn't fix the problem of my last comment. So we definitely need to rewrite the IntroActivity for proper instance saving and restoring support.

**Comment by HeinrichReimer** [comment]
I switched from using `FragmentPagerAdapter` to using `FragmentStatePagerAdapter` in e6fe290. This should keep `Fragment`s in memory. I have to look into restoring pager position though.

**Comment by HeinrichReimer** [comment]
The main issue is that the displayed `Fragment` is the old one loaded from `FragmentManager` and the code that checks if  users are allowed to go to the next page is the new one returned because `onCreate()` gets called on `IntroActivity`

**Comment by HeinrichReimer** [comment]
We could either try to detect if an old but matching `Fragment` is already existing in `FragmentManager` in `SlideAdapter.addSlide()`. But that would require us to save a unique ID with every `Slide` which I don't like as it's extra effort for developers implementing this library ...
... or we simply don't use `Fragment` retaining at all but instead create every Fragment again after an orientation change. That's not a problem in particular as the fragments used in an intro won't be very complicated and thus the recreation process would not take too much time...

**Comment by HeinrichReimer** [comment]
(Accidentially closed the issue. Sorry for that!)

**Comment by HeinrichReimer** [comment]
Finally found a solution for the first approach without requiring an ID. Needs some polishing and will be a breaking change so stay tuned for a fix soon.
