### ISSUE TITLE
Apps using this library

### ISSUE THREAD

**Issue by heinrichreimer** [heinrichreimer/material-intro#200]
It may be useful to establish a list of apps that use this intro for others to try it out.

- [**Simply Unroot**](https://play.google.com/store/apps/details?id=de.pinpong.simplyunroot) by @pinpong
- [**Prodigal Music Player**](https://play.google.com/store/apps/details?id=bob.sun.prodigal) by @SpongeBobSun 
- [**Puff Password Utility**](https://play.google.com/store/apps/details?id=sun.bob.leela) by @SpongeBobSun  
- [**QualityGate**](https://play.google.com/store/apps/details?id=com.frontendart.qualitygate.android) by @FrontEndART 
- [**Monitor**](https://play.google.com/store/apps/details?id=com.danielstone.energyhive) by @daniel-stoneuk 
- [**Contact Lenses Time**](https://play.google.com/store/apps/details?id=com.brando.lenti) by @ste23droid 
- [**Antidote Danmark**](https://play.google.com/store/apps/details?id=dk.antidotedanmark) by @AntidoteDanmark
- [**Speed Boost Lite**](https://play.google.com/store/apps/details?id=com.TMillerApps.SpeedBoostLite) by @tjmille2

**Comment by SpongeBobSun** [comment]
My another indie app also used this lib.

https://github.com/PuffOpenSource/Puff-Android

Google Play link - 

https://play.google.com/store/apps/details?id=sun.bob.leela

But seems like I forget to add you in `Puff`'s credit list. Will fix that soon. Sorry.

**Comment by Sleeper9** [comment]
We use this great library in our software quality management application. The link is: [Google play link](https://play.google.com/store/apps/details?id=com.frontendart.qualitygate.android)

**Comment by daniel-stoneuk** [comment]
Awesome library for my niche app Monitor (for monitoring energy consumption and generation).

https://play.google.com/store/apps/details?id=com.danielstone.energyhive

**Comment by HeinrichReimer** [comment]
Once there are significantly many entries here, I'll merge the list into the `README.md`.

**Comment by ste23droid** [comment]
My application about contact lenses uses your library :)
Here it is:

https://play.google.com/store/apps/details?id=com.brando.lenti

**Comment by simonrosted** [comment]
My antidote first aid app uses your library as well :)
https://play.google.com/store/apps/details?id=dk.antidotedanmark
https://github.com/AntidoteDanmark/antidotedanmark-app-android

**Comment by tjmille2** [comment]
My Speed Boost app uses this library!
https://play.google.com/store/apps/details?id=com.TMillerApps.SpeedBoostLite

**Comment by heinrichreimer** [comment]
@pinpong, @SpongeBobSun, @Sleeper9, @daniel-stoneuk, @ste23droid, @simonrosted, @tjmille2:  
I merged the list into `README.md`

**Comment by joeykrim** [comment]
Using this library (thanks!) in Root Checker (50M+ downloads): https://play.google.com/store/apps/details?id=com.joeykrim.rootcheck

**Comment by chimbori** [comment]
Awesome! Please submit PRs to README.md as a way of continuing to build a list of apps using this library.
