### ISSUE TITLE
Add your library to AboutLibraris by Mike Penz?

### ISSUE THREAD

**Issue by ste23droid** [HeinrichReimer/material-intro#201]
Hi there,
I've integrated your wonderful library in my app.
Works great and I would like to credit properly your work. I've discovered and i'm using this library https://github.com/mikepenz/AboutLibraries, I think that if you add your library in their library list it'll be easier for all of us to share and credit your work. Your "competitors" of AppIntro already are included in that library list.
Have a nice day :)

**Comment by HeinrichReimer** [comment]
Nice idea!
