### ISSUE TITLE
Hiding back button in FragmentSlide

### ISSUE THREAD

**Issue by odin-** [heinrichreimer/material-intro#202]
Trying to hide the back button in a FragmentSlide created like this:

        addSlide(new FragmentSlide.Builder()
                .background(R.color.background)
                .backgroundDark(R.color.yellow)
                .fragment(RegisterIntroFragment.newInstance())
                .build());

Can it be done?

**Comment by daniel-stoneuk** [comment]
You could use

```java
addOnPageChangeListener(new ViewPager.OnPageChangeListener(){
    @Override public void onPageSelected(int position) { ... }
});
```

and update the visibility of the back button like so if you know which position it's in.

```java
/* Show/hide button */
setButtonBackVisible(true);
/* Use skip button behavior */
setButtonBackFunction(BUTTON_BACK_FUNCTION_SKIP);
/* Use back button behavior */
setButtonBackFunction(BUTTON_BACK_FUNCTION_BACK);
```

Or you could use a NavigationPolicy with the position of the slide:

```java
setNavigationPolicy(new NavigationPolicy() {
    @Override public boolean canGoForward(int position) {
        return true;
    }

    @Override public boolean canGoBackward(int position) {
        return false;
    }
});
```

**Comment by heinrichreimer** [comment]
I would suggest using a navigation policy. If you don't want users to be able to go back from this slide just  block back-navigations using one of the methods stated in the [readme](https://github.com/heinrichreimer/material-intro#block-navigation).

If you also want to hide the button then @daniel-stoneuk's solution is great. (You don't need to call `setButtonBackFunction()` again, just `setButtonBackVisible()` is enough):

```java
addOnPageChangeListener(new ViewPager.OnPageChangeListener(){
    @Override public void onPageSelected(int position) {
        setButtonBackVisible(position != POSITION_TO_HIDE);
    }
});
```

**Comment by odin-** [comment]
I only got fragment slides and the first slide doesn't get a call to onPageSelected

**Comment by odin-** [comment]
Nevermind I'll keep the back button on the first slide.

**Comment by heinrichreimer** [comment]
To block navigation: Again, see _1._ and _3._ of the ["Block navigation" in the readme](https://github.com/heinrichreimer/material-intro#block-navigation)

To hide the back button: If it's for the first slide, *material-intro* automatically hides the back button for you when using `setButtonBackFunction(BUTTON_BACK_FUNCTION_BACK)`, if you need that for any other slide, then a `OnPageChangeListener` should be called.

**Comment by odin-** [comment]
It doesn't hide the button for me. Clearly I'm doing something wrong. I'll investigate.

**Comment by heinrichreimer** [comment]
Uhm, that's not how it should be. Which library version are you using?
This may be related to #199...

**Comment by heinrichreimer** [comment]
Confirmed working: https://github.com/heinrichreimer/material-intro/issues/199#issuecomment-291222298
