### ISSUE TITLE
ButtonCta not working?

### ISSUE THREAD

**Issue by vekexasia** [heinrichreimer/material-intro#204]
I tried a very simple piece of code and wanted the cta to trigger the event (as per documentation) when clicked.

Nothing was called 

![image](https://cloud.githubusercontent.com/assets/200523/25720469/48b7ac2c-310d-11e7-9bdb-2146cc2d3b9f.png)

**Comment by heinrichreimer** [comment]
Please take a screenshot or upload sample code to reproduce this error.

**Comment by trikhatarun** [comment]
I am also having the same problem. Is there a solution to this? 
**Problem:** I created a new application with a new activity file that extends IntroActivity class. I add one slide with some text and a CTA button which starts a new Intent but before that logs the action of click.
Now I start IntroActivity by calling intent from MainActivity and when I click the CTA button, click is not logged and the IntroActivity closes and opens MainActivity again.
