### ISSUE TITLE
Databinding has some problem: NoSuchMethodError: android.databinding.BindingBuildInfo.enableDebugLogs()Z 

### ISSUE THREAD

**Issue by shehroz76** [heinrichreimer/material-intro#206]
![1](https://cloud.githubusercontent.com/assets/18357140/26178553/0f462c8c-3b78-11e7-9762-d76a0cd0dbce.jpg)

**Comment by heinrichreimer** [comment]
This issue is aduplicate of https://github.com/heinrichreimer/material-intro/issues/198. Please make sure to check if the issue was already answered before posting a new issue.
