### ISSUE TITLE
Can't change CTA button

### ISSUE THREAD

**Issue by ferrannp** [heinrichreimer/material-intro#213]
Hi,

I tried to set up a listener:

```java
setButtonCtaClickListener(new View.OnClickListener() {
  @Override
  public void onClick(View v) {
    // Do stuff
  }
});
```

CTA button seems to just do the default behavior no matter what.

Edit:

Ok If I set it up only on the last slide like:

Or in the last slide:

```java
.buttonCtaLabel("Skip")
.buttonCtaClickListener(new View.OnClickListener() {
   @Override
   public void onClick(View v) {
     // Do stuff
   }
})
```
Then it works. The problem with second method though is that button is always visible, I wanted it to hide till some conditions are met and then show it but then, the first listener (global?) has no effect.

**Comment by heinrichreimer** [comment]
@ferrannp In general try to avoid updating the intro while it's showing.
If you really need to update the CTA button you could look in [`SimpleSlide`'s source code](https://github.com/heinrichreimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java). It updates the CTA to request permissions.

**Comment by ferrannp** [comment]
Ok!
