### ISSUE TITLE
How to go to next activity after intro is finished?

### ISSUE THREAD

**Issue by stevewhite21** [heinrichreimer/material-intro#216]
Sorry I'm kind of a noob at importing libraries and understanding their unique codes. I have my slides set up with titles and every thing but after the intro is done how can I jump to the main activity? I've been looking through the sample project but I'm so confused. Please help me anyone.

**Comment by odin-** [comment]
Did you try to call `nextSlide` in your `SlideFragment`? It should finish the activity if you're done and return to the calling activity.

**Comment by stevewhite21** [comment]
How can I know which activity will be called on after the slides are done.

**Comment by odin-** [comment]
Either you have an MainActivity which started the `IntroActivity`, in this case obviously the MainActivity pops up again when you finish and you can do whatever is needed in the MainActivity.

Or as it seems in your case, the IntroActivity is actually your launch activity (as specified in the Manifest)?
Then you need to start a new activity when the last button has been clicked. Perhaps by trying to override the button click using `buttonCtaClickListener` during call to `FragmentSlide.Builder`.

**Comment by stevewhite21** [comment]
I wanted the Cta button to be invisible the whole intro but I'll try it out. Is it possible to hide the Cta button in the first slides then make it visible in the last slide?

**Comment by heinrichreimer** [comment]
@stevewhite21 You can set a CTA button to the `SimpleSlide.Builder` to just change the CTA button for a specific slide.

**Comment by heinrichreimer** [comment]
Refer to the sample app on how to implement a splash screen activity: https://github.com/heinrichreimer/material-intro#splash-screens
