### ISSUE TITLE
Data Binding Library

### ISSUE THREAD

**Issue by meierjan** [heinrichreimer/material-intro#227]
Hey,

I would like to raise the question if we should remove data-binding from this library. I haven't seen any place where this brings a major benefit in this library. For people not using data-binding this is a unnecessary dependency.

What do you think?

I would PR.

**Comment by meierjan** [comment]
@heinrichreimer ?

**Comment by heinrichreimer** [comment]
If you could propose a pull request that would be awesome!
I see your point and I also think that the library could be lighter as it is now.

**Comment by meierjan** [comment]
Okay, I will provide a PR this weekend.

**Comment by heinrichreimer** [comment]
Thank you 😊

**Comment by meierjan** [comment]
I've submitted the PR. Please have a look 👍

**Comment by JRoot3D** [comment]
Is released Library without data binding?

**Comment by meierjan** [comment]
@JRoot3D Not released yet but you can target commit @ jitpack.

**Comment by chimbori** [comment]
Data binding dependency has been removed, thanks @meierjan : ebc6b71

New release coming soon!
