### ISSUE TITLE
failed to resolve com.heinrichreimersoftware:material-intro

### ISSUE THREAD

**Issue by rajeshvinew** [heinrichreimer/material-intro#241]
https://imgur.com/0msF19l
https://imgur.com/L0TMRwA

**Comment by daniel-stoneuk** [comment]
Have you added the Jitpack repository as per the instructions here: https://jitpack.io/#com.heinrichreimersoftware/material-intro

**Comment by rajeshvinew** [comment]
after invalidate cache and restart worked for me
