### ISSUE TITLE
Bug: getInt instead of getLong for ARGUMENT_ID

### ISSUE THREAD

**Issue by MFlisar** [heinrichreimer/material-intro#243]
Here you use `getInt` instead of `getLong`:

https://github.com/heinrichreimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java#L592

Everywhere else you use `getLong` and `putLong`. Above getter throws an exception because the bundle is checking the type

**Comment by heinrichreimer** [comment]
Good catch! Thanks for the pr, I'll check it out soon.

**Comment by heinrichreimer** [comment]
Fixed by PR #244
