### ISSUE TITLE
[Critical] Support AndroidX

### ISSUE THREAD

**Issue by EdricChan03** [heinrichreimer/material-intro#254]
When building an app with the AndroidX library (as well as `material-intro`), an error will occur.

The error in question:
```
error: cannot find symbol class ConstraintLayout
```

**Comment by zacharee** [comment]
Use this format when implementing AndroidX:

```
implementation ('ANDROIDX_DEPENDENCY_STRING') {
    exclude group: 'com.android.support'
}
```

**Comment by JavaCafe01** [comment]
Still getting that error in the build folder...

**Comment by shelland** [comment]
Seems like this issue is still actual? 

implementation ('com.heinrichreimersoftware:material-intro:1.6.2') {
        exclude group: 'com.android.support'
}

(error: package android.support.constraint does not exist)

**Comment by Chan4077** [comment]
It appears that commit d0220b0228aee707c528f69d5a49b165257288df by @adrcotfas has migrated the source to AndroidX. (Or see #266)

Looks like it's up to @heinrichreimer to see if there'll be a new release.

**Comment by rustamsafarovrs** [comment]
Anyone resolved this issue?
error: package android.support.constraint does not exist

**Comment by chintan-mishra** [comment]
Go through the setup process. While modifying the app module's `build.gradle` use 

`implementation 'com.heinrichreimersoftware:material-intro:master-SNAPSHOT'`. 

This solves the issue mentioned here. This way master version is used instead of `1.6.2`. Try this and let me know.

**Comment by sds100** [comment]
Using `master-SNAPSHOT` rather than `1.6.2` fixed the problem for me.

**Comment by soniel2013** [comment]
for me too

**Comment by chimbori** [comment]
Release 2.0.0 is now available with AndroidX support.
