### ISSUE TITLE
Starting IntroActivity

### ISSUE THREAD

**Issue by mxp7064** [heinrichreimer/material-intro#255]
If I understood correctly from other threads - the idea is to first start an activity that we want to show after the intro and then start the IntroActivity. The problem with this is that for a brief moment before the IntroActivity opens we see the previous activity. This is not a huge problem if we are talking about some sort of splash activity that's shown before, but it's really a flawed design if we are talking about some sort of home/main activity. Why would the user need to see that - it looks glitchy and annoying. Does anyone have a solution for this? 
Thank you in advance

**Comment by chimbori** [comment]
You can easily change your flow such that this IntroActivity is shown first, and then on the final slide, you launch the actual home Activity. 

Although a design choice has been recommended by the authors, there is no reason that that is the only possible one. The library certainly supports alternate ones.
