### ISSUE TITLE
Databinding cast that crashes the app?

### ISSUE THREAD

**Issue by preprux** [heinrichreimer/material-intro#256]
Hey there,
Whenever I attempt to extend to app/IntroActivity class, i get this weird exception that seems to be casting the bindings generated for my package and the library's package? It crashes the app.

Caused by: java.lang.ClassCastException: me.morgy.fish.databinding.MiActivityIntroBindingImpl cannot be cast to com.heinrichreimersoftware.materialintro.databinding.MiActivityIntroBinding

**Comment by lhypl** [comment]
wait what the fuck i didn't realize i had another class with the same name omg ._.

**Comment by lhypl** [comment]
Wait a min i saw wrongly there is a issue rip

**Comment by hellboyfa** [comment]
i have the same problem

**Comment by chimbori** [comment]
Until this is fixed, reverting to version 1.6 seems to be an acceptable workaround. Documenting in case others find this useful!

**Comment by edotassi** [comment]
any news?

**Comment by doilio** [comment]
Same error here. any updates on how to fix this?

**Comment by Inversion-NL** [comment]
> Until this is fixed, reverting to version 1.6 seems to be an acceptable workaround. Documenting in case others find this useful!

Updating to 1.6 didn't help.
Currently running 1.5.8 looks like it did the trick.

Thanks for the library!

**Comment by ferrannp** [comment]
Wop! Having this issue in all my devices. What is actually happening?

**Comment by Anutha02** [comment]
I am getting exactly this error. It wwas working fine before with AS 3.1.4, Gradle 4.1, AGP 3.1.4. But today, I updated to AS 3.2, Gradle 4.6, AGP 3.2.0 and it started giving errors... Please someone fix this.

**Comment by EpsilonOrionis** [comment]
Please fix

**Comment by akashpathak** [comment]
Anyone have a work around? Downgrading to 1.5.8 did not work for me.

**Comment by Unpublished** [comment]
Updating to latest master commit (`com.heinrichreimersoftware:material-intro:7221502f1f`) solves it but may be unstable.

**Comment by Anutha02** [comment]
I downgraded to 1.6 with Gradle 4.6 and it worked for me

**Comment by doilio** [comment]
> I downgraded to 1.6 with Gradle 4.6 and it worked for me

`    implementation 'com.heinrichreimersoftware:material-intro:1.6'`
So far, It's Working for me as well. No luck with **1.6.1**

**Comment by captainepoch** [comment]
With AS 3.2, Kotlin 1.2.71 and Gradle 4.6, the downgrade to the 1.6 seems to be a hack to get it working

**Comment by ferrannp** [comment]
Yeah although version 1.6.0 has more bugs than 1.6.1 (like wrong button colors on Lollipop).

**Comment by Spiderbezno** [comment]
I have the same problem, since I updated to Gradle version

**Comment by philbour** [comment]
This is causing my app to crash for all my users, since I updated android studio and gradle. Really need it fixed

**Comment by allato** [comment]
> 
> 
> Updating to latest master commit (`com.heinrichreimersoftware:material-intro:7221502f1f`) solves it but may be unstable.

Could you TAG last commit with a new subversion to update every project?
Tnk for your job

**Comment by simonesessa** [comment]
Works with gradle 4,4 and 'com.android.tools.build:gradle:3.1.0'.
Is there a fix for gradle 4.6?

**Comment by Aeg0nTargaryen** [comment]
Same here
Downgraded library to 1.6 with Gradle 4.6 and it worked.
any fixes for 1.6.2?

**Comment by msahil432** [comment]
Using 1.6, solved my issue.
I am using AS 3.3 and com.android.tools.build:gradle:3.3.0

**Comment by VladimirWrites** [comment]
https://github.com/heinrichreimer/material-intro/issues/261#issuecomment-470543841

**Comment by chimbori** [comment]
Data binding dependency has been removed, thanks @meierjan : ebc6b7192d5586fad7a170e0a24788cd8bb41f41
