### ISSUE TITLE
Custom layout for parallax slides

### ISSUE THREAD

**Issue by adrcotfas** [heinrichreimer/material-intro#265]
Is there any way of using a custom layout with parallax, for example using multiple images?

**Comment by heinrichreimer** [comment]
You may want to take a look at the parallax implementation:
https://github.com/heinrichreimer/material-intro/tree/master/library/src/main/java/com/heinrichreimersoftware/materialintro/view/parallax
Main part of it is the `Parallaxable` class.

**Comment by adrcotfas** [comment]
I managed to achieve what I was looking for by including custom Views into a ParallaxLinearLayout and using it in the slides.
