### ISSUE TITLE
not showing app intro

### ISSUE THREAD

**Issue by Rahvayana** [heinrichreimer/material-intro#268]
i've add the manifest.
        <activity
            android:name=".MainIntroActivity"
            android:theme="@style/Theme.Intro" />
then make MainIntroActivity.java like this.

public class MainIntroActivity extends IntroActivity {
    @Override protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setFullscreen(true);
        addSlide(new SimpleSlide.Builder()
                .title("Title")
                .description("This is Description")
                .image(R.drawable.ic_launcher_background)
                .background(R.color.colorPrimary)
                .scrollable(false)
                .permission(Manifest.permission.CAMERA)
                .build());
        setButtonBackVisible(true);
        setButtonNextVisible(true);
    }
but the app intro not showing at all, what missing?
Thanks

**Comment by TangLiuRain** [comment]
Have you solve it? I also met the some question.

**Comment by TangLiuRain** [comment]
Please remove "setContentView(R.layout....)" , and try to run again.

**Comment by chimbori** [comment]
Please follow the recommended solution, and re-open if your issue still is pending.
