### ISSUE TITLE
No new release since 1.6.2, more than 2 years & 55 commits ago?

### ISSUE THREAD

**Issue by chimbori** [heinrichreimer/material-intro#274]
There has been a lot of activity on this repo since the last release, including several critical improvements (e.g. AndroidX) and crashing bug fixes (the data binding issue).

Is there a plan to issue a new release any time soon?

(We don’t want to depend on `-SNAPSHOT` because we need to be confident of what we’re pulling in, so an actual release tag would be super useful. Thanks!)

```
Release 1.6.2
@heinrichreimer heinrichreimer released this on Mar 21, 2017 · 55 commits to master since this release
```

**Comment by chimbori** [comment]
To clarify, while I could just fork this and release updates, I think it will be better for the community to continue to pull this from its current coordinates. If you’d like my help in maintaining this repo, I’m happy to chat more!

**Comment by heinrichreimer** [comment]
Thanks for your help!

**Comment by chimbori** [comment]
Thanks @heinrichreimer for granting me ownership! I’m now merging in pending pull requests, updating dependencies, and will soon push a 2.0 as in #275
