### ISSUE TITLE
Considering bumping new version to 2.0.0 because of the move to AndroidX

### ISSUE THREAD

**Issue by chimbori** [heinrichreimer/material-intro#275]
What do you think, @heinrichreimer ?

(Thanks for giving me repo access, hoping to get a new release posted soon! I’ll quickly go through recent commits to see what has been added since 1.6.2).

**Comment by heinrichreimer** [comment]
Great suggestion 👍

**Comment by chimbori** [comment]
Fixed in 57e6d73b3
