### ISSUE TITLE
Failed to resolve: com.heinrichreimersoftware:material-intro:x.y.z 

### ISSUE THREAD

**Issue by digitandolentamente** [heinrichreimer/material-intro#277]
I can't use it, any solution?
even changing version, clearing cache, or even doing another project. he doesn't sync
![Anotação2](https://user-images.githubusercontent.com/55878597/65914541-f28ed000-e3a7-11e9-9822-c688726f290f.png)
![Anotação](https://user-images.githubusercontent.com/55878597/65914542-f28ed000-e3a7-11e9-8e9c-bf5786ff1bdd.png)

**Comment by chimbori** [comment]
Have you tried the solution presented by Android Studio in your screenshot?

**Fix Gradle wrapper and re-import project**. Click that link, follow the rest of the instructions.

**Comment by digitandolentamente** [comment]
yes, and yet the error still remains.
I even did another project from 0, thinking it might be something wrong with the project itself.
but the failure still persists

**Comment by chimbori** [comment]
And just to confirm the obvious, you did replace the `x.y.z` with the actual latest version code, correct?

**Comment by digitandolentamente** [comment]
yes, according to the second picture,
I even left an earlier version (5.1.1), to see if it updated,
even set to 5.4.1. but still error syncing
I did a third project, and Aidna keeps going wrong.
can you add it manually?

**Comment by eraldoakosoft** [comment]
implementation 'com.heinrichreimersoftware:material-intro:2.0.0'

**Comment by heinrichreimer** [comment]
I recommend to check the JitPack page:
https://jitpack.io/#com.heinrichreimersoftware/material-intro
Version 2.0.0 seems to be available there.
And if you want to go absolutely safe, you can also use the GitHub URL for JitPack:
https://jitpack.io/#heinrichreimer/material-intro
