### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by simonrosted** [HeinrichReimer/material-intro#3]
Hi there,

great library!!

Would it be possible to change the "skip" button to a "previous" button. Further, if possible, it'd be great if the "previous" button would hide on the first slide and the "next" button hide on the last slide.

My intention is to use this library more as a presentation/guide (i my case a guidance on how to perform first aid).

Cheers and thanks in advance!

**Comment by HeinrichReimer** [comment]
Great idea! I'll add an option to disable the skip button and the finish button.

**Comment by HeinrichReimer** [comment]
Just pushed an update containing options to enable/disable skip and finish using `setSkipEnabled(boolean skipEnabled)` and `setFinishEnabled(boolean finishEnabled)`.
