### ISSUE TITLE
Is it possible change the color of bullet?

### ISSUE THREAD

**Issue by Spiderbezno** [HeinrichReimer/material-intro#37]
Is it possible change the color of bullet?

**Comment by daniel-stoneuk** [comment]
What do you mean by "the bullet"?

**Comment by HeinrichReimer** [comment]
Do you mean the pager indicator dots?

**Comment by Spiderbezno** [comment]
Yes the page indicator

**Comment by HeinrichReimer** [comment]
That could be an option...
Another option would be to have the grey dots always the color of the status bar and changing the white dots to grey similar to the way the status bar switches between light mode/dark mode based on the luminance of the background.
I kinda think that's the better way as it would be easier for devs implementing material-intro to rely on readability without having to deal with foreground colors at all

**Comment by HeinrichReimer** [comment]
Indicator colors are automatically set dependent on what background color you set to ensure maximum contrast.

**Comment by Spiderbezno** [comment]
And this change will appear in the version 1.4??

**Comment by HeinrichReimer** [comment]
Yes, but you can already use the feature now by using this dependency: https://jitpack.io/#com.heinrichreimersoftware/material-intro/-1.3-gae3e9e8-4

**Comment by Spiderbezno** [comment]
OK thx

**Comment by Spiderbezno** [comment]
I tried, and the major part change color correctly, but the point selected in a background white-grey
![screenshot_20160502-133113](https://cloud.githubusercontent.com/assets/3285472/14953461/20c012aa-106a-11e6-85ba-a1ea542b1f4b.png)
 is not visible

**Comment by HeinrichReimer** [comment]
You need to define another `backgroundDark`. E.g. try #E0E0E0 and it should look better.

**Comment by Spiderbezno** [comment]
Background dark in my style?
You need to define another `backgroundDark`. E.g. try #E0E0E0 and it should look better.

---

**Comment by HeinrichReimer** [comment]
Yes use brighter shade of grey instead of black

**Comment by Spiderbezno** [comment]
THX, now is perfect
![screenshot_20160503-085714](https://cloud.githubusercontent.com/assets/3285472/14976563/09f4f45c-110d-11e6-8fd2-8f7c9419bf4c.png)
