### ISSUE TITLE
Support title and description styling

### ISSUE THREAD

**Issue by ericwjr** [HeinrichReimer/material-intro#41]

**Comment by HeinrichReimer** [comment]
If you refer to `SimpleSlide` this isn't a planned feature. If you want to have another text appearance just use `SimpleSlide.Builder.layout()` and set your own layout with the text style you want.

**Comment by HeinrichReimer** [comment]
If you have any further questions please comment here.

**Comment by ericwjr** [comment]
Sounds good...thanks for quick response.
