### ISSUE TITLE
Add option to completely hide skip and finish buttons

### ISSUE THREAD

**Issue by mahmooddagga** [HeinrichReimer/material-intro#43]
how can i hide skip and finish button ???

i want to hide it in all pages .....

i tried 
        /* Enable/disable skip button */
        setSkipEnabled(false);

        /* Enable/disable finish button */
        setFinishEnabled(false);

i think its not working ,, it visible but not enable

**Comment by HeinrichReimer** [comment]
Possible duplicate of #3 
Please attach a screenshot of the issue, so that I can better understand it.

**Comment by mahmooddagga** [comment]
setSkipEnabled(false);
its only hide from first page ..

i want to hide  all button in all pages .....
skip back finish ...

and thanks

**Comment by mahmooddagga** [comment]
i think it can be done quickly ,, set visibility gone for (skip ,back ,finish, next)

thank you very much ,,  i am waiting for new release ,, i hope it soon

**Comment by mahmooddagga** [comment]
also if we can hide circular indicator in specific page or last page , will be great

**Comment by HeinrichReimer** [comment]
So you basically want to hide the buttons at all?

**Comment by mahmooddagga** [comment]
yes , thank for great library

**Comment by HeinrichReimer** [comment]
Use the new methods `setButtonBackVisible()` and `setButtonNextVisible()`.
