### ISSUE TITLE
There should be a way to know when the finish button is pressed

### ISSUE THREAD

**Issue by CarlosJJR** [HeinrichReimer/material-intro#48]
It would be really useful to know when the finish button is pressed. Right now the only way to know is overriding nextSlide but it doesn't work for all cases. It could be a callback or a public method that the user can override, maybe just change the signature of finishIfNeeded to public? That would be really helpful.

**Comment by HeinrichReimer** [comment]
I imagine a use case where this would be required. When the finish button I'd pressed the activity finishes so there shouldn't be any callback invoked then normally.

**Comment by HeinrichReimer** [comment]
*I can't imagine

**Comment by larrytech7** [comment]
I think there needs to be a callback that users can respond to when the special finish button is pressed, like onSlideFinish() or something. It can be really useful. Right now i don't even know how to finish the slide and start my next activity

**Comment by ercsoftware11** [comment]
@larrytech7 I agree, i do think there should be a function where we can execute tasks (such as shared preference modifications) after the finish button has been pressed. Also, the activity you want to visible after finishing the intro, has to be the one called at the beginning. You can use the FORWARDING_INTO string (see the example code).

**Comment by HeinrichReimer** [comment]
@larrytech7 @ercsoftware11 If you have to modify some shared preferences or save something in a database, it would just be fine to override `onDestroy()` as you would do in any other activity. For listening slide changes please use a `ViewPager.OnPageChangeListener` or `FadeableViewPager.OnOverscrollPageChangeListener` if you want to listen for the fade at the end too.

@CarlosJJR Your usecase should also work with `ViewPager.OnPageChangeListener`.
