### ISSUE TITLE
Force close when not supplying all options to SimpleSlide.Builder

### ISSUE THREAD

**Issue by Maxr1998** [HeinrichReimer/material-intro#5]
Crashes in Fragment constructor when loading Resource ids from Fragment arguments, as some of them are 0x0.

**Comment by HeinrichReimer** [comment]
You must supply at least a background color, a title, a description and an image.
`SimpleSlide` is not meant to be used without arguments.

**Comment by Maxr1998** [comment]
Sure, but shouldn't there at least be some kind of check or default text, not just a plain crash?

**Comment by HeinrichReimer** [comment]
It throws an `IllegalArgumentException` saying that you must provide at least a background, title, description and image.

**Comment by Maxr1998** [comment]
Hm, ok. In my opinion that's not ideal, but ok. I don't want to meddle in your work, especially as it's so wonderful :)

**Comment by HeinrichReimer** [comment]
What should be the desired behavior?

**Comment by Maxr1998** [comment]
Well, if the id is null, just supply no text. Should I create a PR?

**Comment by HeinrichReimer** [comment]
I would appreciate that

**Comment by HeinrichReimer** [comment]
@Maxr1998 Your pull request contains only one small error. Would you please fix that, so that I can merge it?

**Comment by Maxr1998** [comment]
Oops, I'm terribly sorry. Didn't see the notifications the last days. Did you fix the issue yourself?

**Comment by HeinrichReimer** [comment]
No, I can't edit your pill request... Would be happy if you edit it

**Comment by Maxr1998** [comment]
I fixed it in my code, but I guess I also need to send a new pull request..
