### ISSUE TITLE
Strings to Skip Button and Next Button

### ISSUE THREAD

**Issue by NajeraP95** [HeinrichReimer/material-intro#50]
Add an option to chance the image of skip button and next button to text,example Skip and Next

**Comment by HeinrichReimer** [comment]
This is a won't fix because it would break the simplicity of the intro.
However you can translate the default (English) strings that appear on long click by overwriting
```xml
<string name="mi_content_description_skip">Skip</string>
<string name="mi_content_description_back">Skip</string>
<string name="mi_content_description_next">Next</string>
<string name="mi_content_description_next_finish">Next/Finish</string>
```
