### ISSUE TITLE
Parallax effect (Feature request)

### ISSUE THREAD

**Issue by JovieBrett** [HeinrichReimer/material-intro#55]
Hi, I'd like to request a new feature where we can have a parallax effect while sliding between fragments like this: 
![ezgif com-resize](https://cloud.githubusercontent.com/assets/5206764/15627509/0be55552-2519-11e6-9af4-126d0b4093fe.gif)
Because it's such a nice effect to have this haha

**Comment by HeinrichReimer** [comment]
Working on this, will be ready tomorrow.
