### ISSUE TITLE
Screen rotation resets intro slides in splash screen demo 

### ISSUE THREAD

**Issue by Sleeper9** [HeinrichReimer/material-intro#58]
Whenever I rotate the screen during the intro slides, the intro starts again at the initial position. I follow the example code and add my slides in `onCreate()`. I tried to wrap the code into a 
`if (null == savedInstanceState) { ... }`, but then I get an exception:

```
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 0
 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2689)
 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
 android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4458)
 android.app.ActivityThread.access$1000(ActivityThread.java:177)
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
 android.os.Handler.dispatchMessage(Handler.java:102)
 android.os.Looper.loop(Looper.java:145)
 android.app.ActivityThread.main(ActivityThread.java:5938)
 java.lang.reflect.Method.invoke(Native Method)
 java.lang.reflect.Method.invoke(Method.java:372)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
by: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 0
 java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
 java.util.ArrayList.get(ArrayList.java:308)
 com.heinrichreimersoftware.materialintro.slide.SlideAdapter.getBackground(SlideAdapter.java:93)
 com.heinrichreimersoftware.materialintro.app.IntroActivity.getBackground(IntroActivity.java:752)
 com.heinrichreimersoftware.materialintro.app.IntroActivity.updateBackground(IntroActivity.java:367)
 com.heinrichreimersoftware.materialintro.app.IntroActivity.onPostCreate(IntroActivity.java:125)
```

**Comment by HeinrichReimer** [comment]
Can't confirm this on material-intro 1.5.1 running Nexus 5X Android N

**Comment by Sleeper9** [comment]
I just checked out the latest master and this problem appears on Nexus 7 @ Android 6.0.1 (and other lower API levels like 5.0, 4.x as well). Here is a sample gif recording of the _Fake splash screen_ functionality; I rotate the screen two times and pressing the device Back button several times then. You 
can see that the "older" intro screens are still there after I finish a rotated one.

![ezgif-3645377597](https://cloud.githubusercontent.com/assets/3670641/15658959/72dfbf30-26c3-11e6-8ce4-5caaac30835e.gif)

**Comment by HeinrichReimer** [comment]
Yep this is most likely a problem with the splash screen demo as this issue doesn't occur when starting an intro manually e.g. when pressing "Start intro" in the demo.

**Comment by Sleeper9** [comment]
Ah, I see, indeed. But I found another strange thing: the _Get started_ button and the page indicator dots disappear in the "Start intro" demo if you rotate the device any slide other than the first and does not appear again until you go back to the first slide and rotate again.

**Comment by HeinrichReimer** [comment]
We should have another issue for that
