### ISSUE TITLE
"Next" FAB shows both checkmark and arrow when only using one page

### ISSUE THREAD

**Issue by Maxr1998** [HeinrichReimer/material-intro#6]

**Comment by HeinrichReimer** [comment]
Please provide a screenshot. This bug is potentialy fixed by f2143a0ccd40c2a01ccd6392a8200c2314be7d26.

**Comment by Maxr1998** [comment]
I will do that later today, but maybe I'll check first if it's already fixed.

**Comment by Maxr1998** [comment]
Fixed in latest sources.
