### ISSUE TITLE
Text buttons instead of image buttons

### ISSUE THREAD

**Issue by adrcotfas** [HeinrichReimer/material-intro#60]
Hi,
I would like to have the possibility to chose the intro button style.
Also, I would like to have the option to align the left instead of centered, as it is in the current version.
For example (Google Drive intro):
https://drive.google.com/open?id=0B1coFw2JziMJOHY0dUhOSE82ZGM
- text buttons vs FAB
- centered summary text vs aligned to the left

Thanks!

**Comment by HeinrichReimer** [comment]
The library is meant to represent the "Top User Benefits" pattern from the material guidelines: https://www.google.com/design/spec/growth-communications/onboarding.html#onboarding-top-user-benefits.
I may add another button style but this is definitely low priority.
You can modify the slide layout by calling `SimpleSlide.Builder.layout()`.
