### ISSUE TITLE
Strange style in  lasst version 1.5.1

### ISSUE THREAD

**Issue by Spiderbezno** [HeinrichReimer/material-intro#62]
My Slide seems like that in version 1.4
![screenshot_20160531-090328](https://cloud.githubusercontent.com/assets/3285472/15666366/c3599d26-2710-11e6-85a7-6dae356e8e65.png)

and in version 1.5.1 like that(whit a strange space in the bottoms
![screenshot_20160531-091657](https://cloud.githubusercontent.com/assets/3285472/15666372/d40cf62c-2710-11e6-9d8f-b89bcf89e61e.png)
)

**Comment by HeinrichReimer** [comment]
You have to use a slide background color. Having a background image is not supported in this library as it is not part of the material guidelines.
