### ISSUE TITLE
 deprecated setSkipEnabled(true);    setFinishEnabled(true);

### ISSUE THREAD

**Issue by Spiderbezno** [HeinrichReimer/material-intro#67]
Who is the new methods??

**Comment by TheDorkKnightRises** [comment]
For showing a Skip button one should use:

```
setButtonBackVisible(true);
setButtonBackFunction(BUTTON_BACK_FUNCTION_SKIP):
```

For a Finish button:

```
setButtonNextVisible(true);
setButtonNextFunction(BUTTON_NEXT_FUNCTION_NEXT_FINISH);
```

The button to the left (in LTR mode) now has two modes, `BUTTON_BACK_FUNCTION_SKIP`(skips the intro) or `BUTTON_BACK_FUNCTION_BACK` (goes back to previous slide).
The button to the right similarly has two modes, `BUTTON_NEXT_FUNCTION_NEXT` (disappears on final slide) or `BUTTON_NEXT_FUNCTION_NEXT_FINISH` (where it shows Finish button on final slide)

**Comment by Spiderbezno** [comment]
Ok THX

**Comment by HeinrichReimer** [comment]
Couldn't describe this better, thanks @TheDorkKnightRises

**Comment by TheDorkKnightRises** [comment]
Glad to help @HeinrichReimer :)
