### ISSUE TITLE
Version 1.5 can't be found for gradle

### ISSUE THREAD

**Issue by Discover-** [HeinrichReimer/material-intro#69]
When trying to compile version 1.5 through Gradle it says it cannot find the repository. Using version 1.5.2 works fine.

**Comment by Sleeper9** [comment]
Why do you need v1.5? I'd suggest to use 1.5.2, as it contains a number of important bug fixes.

**Comment by Discover-** [comment]
Because 1.5 was linked to in the README.

**Comment by Sleeper9** [comment]
Yeah, I see; @HeinrichReimer should update the gradle dependency in README.md to 1.5.2 as well.

**Comment by HeinrichReimer** [comment]
I'll do that.
However if you want to use older versions you should be able to.
v1.5 is on JitPack. Have you checked your gradle files? You have to add JitPack as a repository.
Check out JitPack for available releases and how to add JitPack libraries to your project: https://www.jitpack.io/#com.heinrichreimersoftware/material-intro

**Comment by Discover-** [comment]
I did and unlike 1.5.2, 1.5 can't be found which is why I created this issue.

**Comment by HeinrichReimer** [comment]
https://github.com/HeinrichReimer/material-intro/commit/2b4de015872bb9c430a675baf63b1901f8175e7c

**Comment by HeinrichReimer** [comment]
I guess this is an issue with JitPack... Anyway, you should use 1.5.2 :smile:

**Comment by Discover-** [comment]
Alright, will keep on 1.5.2. Thanks for the lib, I like it so far.

I've got another issue but I feel like it's quite unique, again. When I am at the last slide and I finish the introduction, it closes the app after sliding it away. How should I get rid of this?
