### ISSUE TITLE
Custom done action

### ISSUE THREAD

**Issue by lonja** [HeinrichReimer/material-intro#72]
Can I set custom function on `buttonNext` click when last slide active?

**Comment by HeinrichReimer** [comment]
You can override `onDestroy()` in your `IntroActivity` or use a combination of `startActivityForResult()` and `onActivityResult()` in your calling activity to perform actions at the moment the intro finishes and the `IntroActivity` closes.
To block finishing the intro use a `NavigationPolicy`.

**Comment by lonja** [comment]
OK, thank you for quick response.
