### ISSUE TITLE
FragmentSlide with full screen image as background

### ISSUE THREAD

**Issue by Tripwire999** [HeinrichReimer/material-intro#75]
Hi,

I'm still using 1.2.1 of your library because I can use a custom fragment with a full screen image as background. I know this isn't really default material, but I would like to know how to do this in the latest version of your library? When I update to the latest version (1.5.3) it seems my fragment is always above the navigation items on the bottom whereas in the 1.2.1 version custom fragment is behind the bottom navigation items.

**Comment by HeinrichReimer** [comment]
This is a behavior changed I made to make it easier to use custom fragments/layouts with **material-intro**.

You should not use a full height image as this is *against* the [**Material guidelines**]().
Here's an example on how it should look if you add an image to the slide:

|Full width image|Simple image|
|---|---|
|![Full width image](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B1PhAWhtrRTrNlFYSUxzaHl4M1E/Best-Practices-5.png)|![Simple image](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B1PhAWhtrRTrUUNkUF9KWTQ5SkU/patterns_usereducation_03_DesignMobilePortrait.png)|
