### ISSUE TITLE
Throw an error if no background is given to SimpleSlide.Builder

### ISSUE THREAD

**Issue by pbeckmann** [HeinrichReimer/material-intro#76]
Hey,

you developed a really great library.

There ist just one annoying thing for beginners. If i don't supply a background color to the SimpleSlide.Builder and run the generated code on any device (tested on 1+1 with CM13 and several emulators i got an RessourceNotFoundException.

My suggestion:
- Either documentate this behavior in the Readme
- Or throw a more helping message than the system does.

If wished, i can create a pull request.

Greetings

**Comment by HeinrichReimer** [comment]
Yeah, you can create a pull request for that. Look at [`FragmentSlide.Builder.build()`](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/FragmentSlide.java#L125) on how this may look. (Think I have simply missed to implement this in `SimpleSlide` too :smile:)
