### ISSUE TITLE
Swipe error if previously blocked

### ISSUE THREAD

**Issue by pbeckmann** [HeinrichReimer/material-intro#77]
Hey,

- I created a custom fragment, cause i want the users to read the entire page and check a checkbox before go on. It contains a smal text and a checkbox.
- I use in internal variable to detect if the checkbox is used. If the value of the checkbox changes- i change the internal var to this value.

- In the function canGoForward i just return the internal value.

Problem: If the user checks the checkbox the swipe forward is not working anymore, Until he went back or forward with the buttons/swipe back.

Greetings

**Comment by HeinrichReimer** [comment]
Let your `Fragment` extend [`SlideFragment`](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/app/SlideFragment.java).
Then you can call `updateNavigation()` from your fragment code to notify the `IntroActivity` of the `canGoForward` change.
You can even call `nextSlide()` then to immediately go to the next slide when the user checks the checkbox.
