### ISSUE TITLE
How to make it so that finishing the introduction just starts an activity

### ISSUE THREAD

**Issue by Discover-** [HeinrichReimer/material-intro#78]
When I am at the last slide and I finish the introduction, it closes the app after sliding the whole app away.

How to make it so that finishing the introduction just starts an activity?

**Comment by HeinrichReimer** [comment]
Please refer to the splash screen [sample](https://github.com/HeinrichReimer/material-intro/blob/master/app/src/main/java/com/heinrichreimersoftware/materialintro/demo/FinishActivity.java).
Basically you need to start the activity you want to show after finishing the intro first and then start the intro "above" it.
