### ISSUE TITLE
How to open activity after the last slide?

### ISSUE THREAD

**Issue by EpsilonOrionis** [HeinrichReimer/material-intro#8]

**Comment by HeinrichReimer** [comment]
If you want to open a different activity after the last slide you could do that by overriding your activity's `onDestroy()` method or by starting two activities when you launch the intro if you want to be able to see the fade effect on your new activity. I can post a little code sample here if you want.

**Comment by EpsilonOrionis** [comment]
Done, thank you

**Comment by CeJienAJPC** [comment]
Would be nice, if sample code is provided for starting a new activity (after the last slide) by overriding the onDestroy()
