### ISSUE TITLE
Start New Activity on Done button

### ISSUE THREAD

**Issue by inceptiveDipak** [HeinrichReimer/material-intro#82]
On Finish of app introduction on last slide there is done button on it i want to start brand new activity.
Thanks for help in advance

**Comment by HeinrichReimer** [comment]
Duplicate of #78

**Comment by HeinrichReimer** [comment]
> Please refer to the splash screen sample.
> Basically you need to start the activity you want to show after finishing the intro first and then start the intro "above" it.
