### ISSUE TITLE
CanGoForward true on permissions slide

### ISSUE THREAD

**Issue by addrum** [HeinrichReimer/material-intro#86]
Not sure if I've missed something in the docs or examples but is it possible to to have canGoForward to be true on a slide that defines a permission? I've got the following but it's still prevents me from proceeding:

`addSlide(new SimpleSlide.Builder()
                .title(R.string.slide3Title)
                .description(R.string.slide3Desc)
                .permission(Manifest.permission.ACCESS_FINE_LOCATION)
                .image(R.mipmap.ic_launcher)
                .background(R.color.colorPrimary)
                .backgroundDark(R.color.colorPrimaryDark)
                .canGoForward(true)
                .build());`

**Comment by pbeckmann** [comment]
Hey,

at least, it should be possible, if you extend the existing SimpleSlide and overwrite the canGoForward method.

Greetings.

**Comment by HeinrichReimer** [comment]
I prefer to say it is _hackable_. Actually you should **not** use [`SimpleSlide.Builder.permission()`](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java#L258) for requesting permissions that are not crucial for your app (aka **runtime permissions**).

#### Two usecases:

1. Your app **can't work without** the specific permission e.g. the camera permission if you have a camera app. Please use [`SimpleSlide.Builder.permission()`](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java#L258)  or [`SimpleSlide.Builder.permissions()`](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java#L253) that _intentionally_ blocks going forward as long as the permission is not granted.
2. The permission you want is **optional** e.g. your users can activate location services to improve the app experience. Use [_runtime permissions_](https://developer.android.com/training/permissions/requesting.html#perm-request) instead at the point your app needs the permissions.

_(Check out the ["Permissions Best Practices"](https://developer.android.com/training/permissions/best-practices.html) if you've heard of runtime permissions the first time.)_

**Comment by addrum** [comment]
@HeinrichReimer thanks. How can I use the same button style then in a custom slide fragment?

**Comment by HeinrichReimer** [comment]
You should check out https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/app/ButtonCtaFragment.java

**Comment by addrum** [comment]
@HeinrichReimer I'm sorry to bug again, but I don't quite know how what you linked helps. Is there a button style I can specify in the xml?

**Comment by HeinrichReimer** [comment]
Just implement `ButtonCtaFragment`. The CTA button is not a built-in feature of `FragmentSlide` yet. Please create another issue if you need that and I'll see if I can implement it.

**Comment by addrum** [comment]
@HeinrichReimer Do I just have to implement it? I've implemented it in my SlideFragment but it doesn't show. Do I need to provide a builder to the custom SlideFragment?

**Comment by HeinrichReimer** [comment]
You have to implement it in the `Fragment` you want to show via `FragmentSlide.Builder.fragment()`.
Use the implemented methods to return the click listener and either a `CharSequence` or a string resource label. If the listener is missing or no label is set no button will be shown.

**Comment by HeinrichReimer** [comment]
If you have any **other** question not targeting *this specific* issue ("CanGoForward true on permissions slide") please create a **new** issue for it in order to keep things organized and accessible to everyone.
I will **not** answer questions not belonging to *this* issue in this thread.
