### ISSUE TITLE
Visual Glitch after Finish button is clicked

### ISSUE THREAD

**Issue by CeJienAJPC** [HeinrichReimer/material-intro#88]
After clicking the _Finish Button_, the _Next_ and _Previous_ button **remain visible (in their default black color)** for 200 to 500 ms approximately before disappearing.

Initially, I thought this glitch was due to my code. However, I am noticing the same glitch in the demo .apk provided by you. Any idea?

Regards

ps: I have been testing my code and your demo apk on pre-kitkat devices (version 17)

**Comment by HeinrichReimer** [comment]
Can you confirm that issue even after 2facd238e3d663da430427a967c50c9ac7918589? This is most likely already fixed in 1.5.5.
The demo.apk is not up to date, my bad.

**Comment by HeinrichReimer** [comment]
This bug is already fixed in **1.5.5**

**Comment by CeJienAJPC** [comment]
sorry for getting back late. Thanks for the 1.5.5 update. The issue has been resolved (partially). On pressing the finish button (in the last fragment), a blank screen appears before starting the next activity. The blank screen with white background doesn't belong to the activity that holds the custom fragments.

I tried changing the background color of the activity to match the background color of the last custom fragment. The blank screen with white background doesn't seem to go away. Hence this issue seem to have been resolved only partially

Thanks again

**Comment by CeJienAJPC** [comment]
Update: version 1.5.6

this issue is yet to be resolved completely. The whitesceen exists nearly for a second and then switches to next activity

**Comment by HeinrichReimer** [comment]
I think what you are refering to is that the next activity only starts after the fade effect has finished. If so you should look into the splashscreen example code. You have to start the intro from the activity you want to be displayed after the intro due to the way android handles the activity lifecycle.

The glitch mentioned in this issue was that the buttons (next, back, CTA) popped up right before finishing the intro because of a wrong modulo operator and was fixed.

**Comment by CeJienAJPC** [comment]
Yes, you are right. Thank you for pointing out the issue. Soon after the last CustomIntro-slide, my main activity starts. Seems the main activity in taking some time to build the layout.

Thanks again

**Comment by HeinrichReimer** [comment]
Please check out the splash screen  sample to achieve the fade effect without any delay after closing the intro.
Again, you have to start your main activity **first** and the intro activity right **after** that.

**Comment by CeJienAJPC** [comment]
> Again, you have to start your main activity first and the intro activity right after that.

Interesting. I will look into this and try the fade effect.  My app starts with launcher activity (for Launch Screen purpose) followed by Tour Activity (with your dependency) and finally the Main activity. The tour activity (as usual) runs only for the first time the app is launched.

Thanks again

**Comment by HeinrichReimer** [comment]
Refer to the sample included. It's basically the same pattern that you use.
[_SplashActivity.java_][27] should be your launcher activity (splash screen), [_SplashIntroActivity.java_][28] should be your tour activity and [_FinishActivity.java_][29] should be your main activity.
The sample also includes the sample code on how to show the intro only once but to re-show it if the user cancelled it using the phones back button.

[27]: https://github.com/HeinrichReimer/material-intro/blob/master/app/src/main/java/com/heinrichreimersoftware/materialintro/demo/SplashActivity.java
[28]: https://github.com/HeinrichReimer/material-intro/blob/master/app/src/main/java/com/heinrichreimersoftware/materialintro/demo/SplashIntroActivity.java
[29]: https://github.com/HeinrichReimer/material-intro/blob/master/app/src/main/java/com/heinrichreimersoftware/materialintro/demo/FinishActivity.java
