### ISSUE TITLE
setSkipEnabled is not found in the IntroActivity.class

### ISSUE THREAD

**Issue by asdfasdfvful** [HeinrichReimer/material-intro#9]

**Comment by HeinrichReimer** [comment]
If you want to use `setSkipEnabled()` you need to use the latest library version. As there is no seperate release yet for this, you can use the latest features with this dependency:
````gradle
dependencies {
    compile 'com.heinrichreimersoftware:material-intro:-SNAPSHOT'
}
````

**Comment by asdfasdfvful** [comment]
ah I see, thanks! Another thing is that this doesn't seem to play well with transparent themes. I know you probably made this without the intent of transparencies, but I'll be looking into it and hopefully I'll find something.

**Comment by HeinrichReimer** [comment]
What do you mean with transparent themes?

**Comment by asdfasdfvful** [comment]
I'm referring to themes that have window backgrounds that are not opaque. If I set theme.intro to show wallpapers and add a translucent background, it's still shown as solid.

**Comment by HeinrichReimer** [comment]
Would you mind creating a seperate issue for that to keep track of?

**Comment by HeinrichReimer** [comment]
This issue specifically can be fixed by changing the dependency so I'm closing it.
