### ISSUE TITLE
Potential bug in version  1.5.5

### ISSUE THREAD

**Issue by mehrdaad** [HeinrichReimer/material-intro#91]
I was using version `1.5.5` of your lib and I was getting several errors which I'm going to explian below, down grading to `1.5.4` solved the problem.  
My `build.gradle`  
 `buildToolsVersion "23.0.2" ` 

my suppport lib dependencies:  

    compile 'com.android.support:design:23.2.0'
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:recyclerview-v7:23.2.0'
    compile 'com.android.support:cardview-v7:23.2.0'

I think updating support tool to 24 created the problem.
I have surfed SO to find a soloution but nothing did work.  
The problems I was encountring:  
Back arrow in toolbar was changed to a white placeholder.  
`CoordanateLayout` caused `XMLPullException` (or sth like that).

**Comment by HeinrichReimer** [comment]
You have to use the latest build tools and compile SDK. This is not a bug with this library. Otherwise the support libraries won't compile correctly.

**Comment by mehrdaad** [comment]
I even updated buildTool to 23.0.3 and support libraries to 24.  
But errors were still persistent.

**Comment by karopass** [comment]
I am facing same issue ! Thanks

**Comment by HeinrichReimer** [comment]
What's your `compileSdkVersion` in your *build.gradle*?

It is highly recommended that you keep the build tools and compile SDK up to date.
The correct settings should currently be:

```gradle
android {
    compileSdkVersion 24
    buildToolsVersion "23.0.3"
    defaultConfig {
        minSdkVersion 15 //Must be >= 15
        targetSdkVersion 24 //Should be the same as compileSdkVersion
    }
}
```

**Comment by HeinrichReimer** [comment]
If you still encounter the issue after updating your compile SDK version please send give us a set of simple steps on how to reproduce the issue.

**Comment by mehrdaad** [comment]
@HeinrichReimer my ``compileSdkVersion `` is 23.  
I don't think forcing clients of a library to have the latest build tool or using another library along with your project is a good indicator of mindful developing of a library.

**Comment by HeinrichReimer** [comment]
It's a common practice that you'll find in almost every Android library to use the latest compile SDK. For example the Android support libraries force you to have the same `targetSdkVersion` as their version number which then forces you to use a `compileSdkVersion` larger than or equal `targetSdkVersion`.
As an Android developer you should always keep your SDK up to date. That's why Android Studio reminds you to update your SDK when a new SDK is available.

**Comment by mehrdaad** [comment]
That's right, I agree. But android N is way too soon to upgrade the lib to.  
Also there shouldn't be any feature that depends on the latest version of android in your lib.

**Comment by HeinrichReimer** [comment]
Nope, the SDK is already finalized with the last developer preview which means you can now upload SDK 14 apps to Google play. This is the time where Google itself recommends developers to update their apps to the latest SDK.
