### ISSUE TITLE
Full screen mode goes away when keyboard opens

### ISSUE THREAD

**Issue by wbervoets** [HeinrichReimer/material-intro#92]
Hi,

I've enabled full screen mode by:   setFullscreen(true);

When I add a SearchView to my custom fragment (set as a slide), and I click on the searchfield (gets focus and shows the keyboard), the status bar is displayed.

Is this normal behaviour?

Thanks
Wim

**Comment by HeinrichReimer** [comment]
This is the normal behavior on Android when the keyboard is shown.
Unfortunately there is no callback for keyboard visibility that can reliably be used in an `Activity` so I think it would be better if you fix that in your custom `Fragment`.
If you would like to fix that here is a workaround by extending `EditText`: http://stackoverflow.com/a/4390592/2037482
Another possible option would be to listen for focus changes on your `EditText`.
