### ISSUE TITLE
Problem in Android 4

### ISSUE THREAD

**Issue by karopass** [HeinrichReimer/material-intro#93]
Hi ! Nice library and easy to implement in app. Its working fine in other version than Kitkat. I am getting application crashed in Android 4.2 as well android 4.4. I have attached logcat for same. Please check and let me know if you have solved or not.
Thanks
[log1.txt](https://github.com/HeinrichReimer/material-intro/files/347744/log1.txt)

**Comment by HeinrichReimer** [comment]
Seems like you are using a Gradle version that doesn't support PNG generation from vector drawables. Check the documentation and update your Gradle version and settings accordingly: https://developer.android.com/studio/write/vector-asset-studio.html

**Comment by karopass** [comment]
Than why you not keep your library minimum 23.2 ? it says that we need minimum 4.4

**Comment by HeinrichReimer** [comment]
The build tools version has nothing to do with the minimum SDK.
You should always use the latest build tools version in your projects independent from wether you use material-intro or not. The latest build tools version ensures maximum compatibility and offers the latest Android build features such as instant run.
The minimum SDK however is only a indicator on which devices the application can run. This library uses min SDK 15 aka ICS MR1 which is the official recommended min SDK nowadays.
To make it more the build tools version is a build time property that won't be visible in the generated APK. 
Please take some time and read the docs about the Gradle build system to understand this better.
