### ISSUE TITLE
Showing CTAButton on custom fragment slide

### ISSUE THREAD

**Issue by addrum** [HeinrichReimer/material-intro#97]
So far I have defined the fragment for the slide and implemented ButtonCtaFragment and it's methods, but the button doesn't show up.

I currently declare the slide:
```
addSlide(new FragmentSlide.Builder()
                .background(R.color.colorPrimary)
                .backgroundDark(R.color.colorPrimaryDark)
                .fragment(DownloadFrequencyFragment.newInstance())
                .build());
```

and have overridden the methods:
```
@Override
    public View.OnClickListener getButtonCtaClickListener() {
        return new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(getContext(), "button", Toast.LENGTH_LONG).show();
            }
        };
    }

    @Override
    public String getButtonCtaLabel() {
        return "Test label";
    }

    @Override
    public int getButtonCtaLabelRes() {
        return 0;
    }
```

What am I missing?

**Comment by HeinrichReimer** [comment]
That's odd...
`DownloadFrequencyFragment`'s class should be declared like this:

```java
public class DownloadFrequencyFragment implements ButtonCtaFragment{
   ...
}
```

**Comment by HeinrichReimer** [comment]
My bad...
I forgot I moved the CTA button code to `ButtonCtaSlide`. I'll add convenience methods to `FragmentSlide`.
Expect a fix this evening.
Sorry for misunderstanding you.

**Comment by HeinrichReimer** [comment]
You can now either keep your code like you have it currently or use `FragmentSlide.Builder.buttonCtaClickListener()`, `FragmentSlide.Builder.buttonCtaLabel()` and `FragmentSlide.Builder.buttonCtaLabelRes()`.

**Comment by addrum** [comment]
@HeinrichReimer thanks! I see this will be in 1.5.6, when will that be released?

**Comment by HeinrichReimer** [comment]
I could release it tomorrow.

**Comment by addrum** [comment]
@HeinrichReimer yes please. I'm using this as part of a university project and I have a demo coming up so would like to have this stuff available.

**Comment by HeinrichReimer** [comment]
Released: https://github.com/HeinrichReimer/material-intro/releases/tag/1.5.6
